// constants/strings.tsx — i18n dictionary + language context (EN / SW / FR / RN)
import React, {
  createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode,
} from 'react';

import { getLang, saveLang } from '@/lib/prefs';

// `name` is what each language calls itself — never translated, so a speaker
// can always find their own language in the list.
export const LANGS = [
  { code: 'en', label: 'EN', name: 'English' },
  { code: 'sw', label: 'SW', name: 'Kiswahili' },
  { code: 'fr', label: 'FR', name: 'Français' },
  { code: 'rn', label: 'RN', name: 'Ikirundi' },
] as const;

export const STRINGS = {
  en: {
    frequencyLabel: 'How often?', freqDaily: 'Every day', freqAlternate: 'Every other day',
    courseEndLabel: 'Until (optional)', courseEndPh: 'YYYY-MM-DD',
    stockLabel: 'Tablets left (optional)', stockPh: 'e.g. 30',
    errCourseDate: 'Enter the end date as YYYY-MM-DD',
    errStock: 'Enter how many tablets are left',
    lateDose: 'late', missedDose: 'missed',
    adherenceTitle: 'Taken as prescribed', lastDaysShort: 'last 30 days',
    dosesTaken: 'doses taken', mostMissed: 'Most missed', refillSoon: 'Refill soon',
    daysLeftShort: 'days left', courseEnds: 'Ends',
    doseTakenAction: 'Taken', doseSnoozeAction: 'Snooze',
    notifChannelName: 'Daily reminders',
    tabLog: 'Log', quickLogTitle: 'What would you like to record?',
    logWater: 'A glass of water', logDose: 'A dose of medicine',
    waterLogged: 'Water logged',
    // ---- dashboard: check-in, routines and the week ----
    energyQuestion: 'And your energy?', energyHint: 'How much have you got left today?',
    moodHint: 'Tap the face that fits',
    back: 'Back',
    routineDone: 'Nice one', routinesAllDone: 'All done',
    statRoutines: 'Routines',
    dailyAverage: 'Daily average', goalDaysMet: 'Goal met',
    medRemindersTitle: 'Medicine reminders', medRemindersSub: 'A reminder at each dose time',
    medRemindersNone: 'Add times to a medicine to get reminders',
    medReminderTitle: 'Time for',
    medRemindersOn: 'Medicine reminders on', medRemindersOff: 'Medicine reminders off',
    remindersScheduled: 'reminders a day',
    pregnancyDisclaimer: 'This is a guide, not medical advice. Keep your antenatal appointments, and contact a clinic if anything worries you.',
    // ---- daily routines ----
    routinesTitle: 'Daily routines', routinesSub: 'The small things you decided to do',
    routinesRowSub: 'Build habits that fit your day',
    addRoutine: 'Add routine', editRoutine: 'Edit routine',
    routineName: 'What is it?', routineNamePh: 'e.g. Morning walk',
    routineDays: 'Which days?', everyDay: 'Every day',
    routineTime: 'Time (optional)',
    noRoutinesToday: 'Nothing due today', noRoutinesTodaySub: 'Add a routine and it will appear here.',
    routineSaved: 'Routine saved', routineRemoved: 'Routine removed',
    removeRoutineTitle: 'Remove this routine?',
    removeRoutineBody: 'Its history will be removed too. This cannot be undone.',
    allRoutines: 'All routines', archived: 'Paused',
    doneToday: 'done today',
    errRoutineName: 'Give the routine a name',
    dayMon: 'Mon', dayTue: 'Tue', dayWed: 'Wed', dayThu: 'Thu', dayFri: 'Fri', daySat: 'Sat', daySun: 'Sun',
    // ---- daily check-in ----
    checkInTitle: 'Daily check-in', checkInSub: 'How are you feeling today?',
    checkInRowSub: 'Mood and energy, in five seconds',
    moodLabel: 'Mood', energyLabel: 'Energy',
    checkInNote: 'Anything to add? (optional)', checkInNotePh: 'e.g. slept badly, headache',
    checkInSaved: 'Saved', checkInToday: 'You checked in today',
    checkInEdit: 'Change it',
    dayStreak: 'day streak', avgMood: 'Average mood', avgEnergy: 'Average energy',
    lastDays: 'Last 14 days', noCheckIns: 'No check-ins yet',
    mood1: 'Awful', mood2: 'Low', mood3: 'Okay', mood4: 'Good', mood5: 'Great',
    energy1: 'Drained', energy2: 'Tired', energy3: 'Okay', energy4: 'Lively', energy5: 'Full of it',
    // ---- pregnancy ----
    pregnancyTitle: 'Pregnancy', pregnancySub: 'Track your weeks and due date',
    pregnancyRowSub: 'Weeks, trimester and due date',
    startPregnancy: 'Start tracking', lastPeriodLabel: 'First day of your last period',
    pregnancyNote: 'Note (optional)', pregnancyNotePh: 'Anything you want to remember',
    weeksPregnant: 'weeks', trimesterLabel: 'Trimester', dueDateLabel: 'Due date',
    overdueLabel: 'Past your due date',
    endPregnancy: 'End tracking', endPregnancyTitle: 'End this pregnancy record?',
    endPregnancyBody: 'You can add a note. Your record stays in your history.',
    outcomeLabel: 'Outcome (optional)',
    pregnancyStarted: 'Tracking started', pregnancyUpdated: 'Updated', pregnancyEnded: 'Record closed',
    pastPregnancies: 'Past records', noPregnancy: 'Not tracking a pregnancy',
    noPregnancySub: 'Start when you are ready. You can stop at any time.',
    errLastPeriod: 'Enter the date in YYYY-MM-DD format',
    // ---- attachments ----
    attachments: 'Attachments', addAttachment: 'Add photo',
    attachmentAdded: 'Photo attached', attachmentRemoved: 'Photo removed',
    removeAttachmentTitle: 'Remove this photo?',
    errUploadNotSet: 'Photo upload is not set up yet.',
    errMediaPermission: 'Allow photo access to attach a picture.',
    // ---- settings screen ----
    settingsSub: 'Reminders, language and how the app looks',
    settingsRowSub: 'Notifications, language, appearance',
    appearanceTitle: 'Appearance', appearanceSub: 'Follows your phone unless you change it',
    darkMode: 'Dark mode',
    unitsTitle: 'Units', unitsSub: 'How weight and height are shown',
    unitsMetric: 'Metric (kg, cm)', unitsImperial: 'Imperial (lb, in)',
    unitsChanged: 'Units updated',
    accountSection: 'Account', appSection: 'App',
    // ---- password reset ----
    forgotTitle: 'Reset your password', forgotSub: 'We will email you a link to set a new one.',
    sendResetLink: 'Send reset link',
    checkInbox: 'Check your inbox', checkInboxSub: 'If that address has an account, it is on its way.',
    resetLinkHint: 'Open the link on this phone to set a new password. It expires in 30 minutes.',
    enterCodeInstead: 'Enter the code instead',
    rememberedIt: 'Remembered it?',
    resetTitle: 'Set a new password',
    resetSubLink: 'Choose a new password for your account.',
    resetSubCode: 'Enter the code from your email, then choose a new password.',
    resetCode: 'Reset code', resetCodePh: 'e.g. 7D8H5X4K',
    errCodeFormat: 'That code should be 8 characters from your email',
    passwordResetDone: 'Password reset successfully',
    // ---- daily reminders ----
    notifTitle: 'Daily reminders', notifSub: 'Water, and a daily word for you',
    notifOn: 'Reminders on', notifOff: 'Reminders off',
    notifDenied: 'Notifications are switched off in your phone settings.',
    notifWaterTitle: 'Time for water',
    notifWaterBody: 'A glass now will keep you going. Small sips count too.',
    notifCareTitle: 'How are you today?',
    notifCareBody: 'Take a moment for yourself. You are doing better than you think.',
    // ---- change password ----
    changePasswordTitle: 'Change password', changePasswordSub: 'Update the password you sign in with',
    currentPassword: 'Current password', newPassword: 'New password',
    confirmPassword: 'Confirm new password',
    passwordChanged: 'Password changed',
    errPasswordMismatch: 'The new passwords do not match',
    errSamePassword: 'Choose a password different from your current one',
    attemptsLeft: 'attempts left',
    forgotCurrent: 'Forgotten your password?',
    useResetInstead: 'Too many attempts. Reset by email instead.',
    resetByEmail: 'Reset by email',
    resetSent: 'If that address is registered, a reset link is on its way.',
    welcomeBack: 'Welcome back',
    loginSub: 'Log in to keep your health on track.',
    createAccount: 'Create account',
    signupSub: 'Start your journey to stronger health.',
    name: 'Full name', namePh: 'e.g. Your Name',
    email: 'Email', emailPh: 'you@example.com',
    password: 'Password', passwordPh: '••••••••',
    create: 'Create account', login: 'Log in',
    forgot: 'Forgot password?',
    remember: 'Remember me',
    noAccount: "Don’t have an account?", haveAccount: 'Already have an account?',
    signup: 'Sign up', loginLink: 'Log in',
    continueWith: 'or continue with',
    terms: 'I agree to the Terms & Privacy Policy',
    errEmail: 'Enter a valid email address',
    errPwShort: 'Use at least 8 characters',
    errName: 'Please enter your name',
    errTerms: 'Please accept the terms to continue',
    errGeneric: 'Something went wrong. Please try again.',
    errSocialUnavailable: 'This sign-in option isn’t available yet. Please use email instead.',
    weak: 'Weak', fair: 'Fair', good: 'Good', strong: 'Strong',
    successTitle: 'You’re all set!', successLoginTitle: 'Welcome back!',
    successSub: 'Taking you to your health dashboard…',
    tagline: 'Your health, made simple.',
    verifyTitle: 'Verify your email',
    verifySub: 'Enter the 6-digit code we sent to',
    verifyCta: 'Verify', resend: 'Resend code', resendIn: 'Resend code in',
    noCode: 'Didn’t get a code?',
    codeErr: 'That code isn’t right. Try again.',
    verifiedTitle: 'Email verified!', verifiedSub: 'Now let’s set up your profile…',
    profileTitle: 'Set up your profile',
    profileSub: 'A few details to personalise your care.',
    addPhoto: 'Add a photo', changePhoto: 'Change photo',
    genderLabel: 'Gender', genderFemale: 'Female', genderMale: 'Male', genderOther: 'Other',
    genderWoman: 'Woman', genderMan: 'Man', errGender: 'Please select your gender',
    heightLabel: 'Height (cm)', heightPh: 'e.g. 170',
    weightLabel: 'Weight (kg)', weightPh: 'e.g. 65',
    finish: 'Finish setup', skip: 'Skip for now', optional: 'Optional',
    profileSaved: 'Profile saved',
    home: 'Home', signOut: 'Sign out',
    goodMorning: 'Good morning', goodAfternoon: 'Good afternoon', goodEvening: 'Good evening',
    quickActions: 'Quick actions', viewAll: 'View all',
    statRecords: 'Records', statMedsDue: 'Meds due', statNextPeriod: 'Next period',
    daysShort: 'd', daysToGo: 'days to go',
    healthRecords: 'Health records', savedLower: 'saved', addFirstRecord: 'Add your first',
    medications: 'Medications', dueToday: 'due today', allDone: 'All done today',
    periodTracker: 'Period tracker', trackWellness: 'Track your cycle',
    myProfile: 'My profile', planFree: 'Free plan', planPremium: 'Premium plan',
    medicationsToday: 'Medications today', noMedications: 'No medications yet',
    doseLogged: 'Dose logged',
    firstNameLabel: 'First name', lastNameLabel: 'Last name', saveChanges: 'Save changes',
    recordsTitle: 'Health records', recordsSub: 'Conditions, allergies and medicines you keep on file',
    addRecord: 'Add record', editRecord: 'Edit record', newRecord: 'New record',
    recordTypeLabel: 'Type', recordNameLabel: 'Name', recordNamePh: 'e.g. Asthma',
    recordNoteLabel: 'Note', recordNotePh: 'Anything worth remembering (optional)',
    typeCondition: 'Condition', typeAllergy: 'Allergy', typeMedication: 'Medicine',
    filterAll: 'All',
    noRecords: 'No records yet', noRecordsSub: 'Add your conditions, allergies and medicines so they are always with you.',
    recordSaved: 'Record saved', recordRemoved: 'Record removed',
    errRecordName: 'Please enter a name',
    removeRecordTitle: 'Remove this record?', removeRecordBody: 'This cannot be undone.',
    cancel: 'Cancel', remove: 'Remove', save: 'Save',
    tabHome: 'Home', tabRecords: 'Records', tabMeds: 'Meds', tabCycle: 'Cycle', tabProfile: 'Profile',
    medsTitle: 'Medications', medsSub: 'What you take, and when',
    addMedication: 'Add medicine', editMedication: 'Edit medicine', newMedication: 'New medicine',
    medNameLabel: 'Medicine', medNamePh: 'e.g. Paracetamol',
    dosageLabel: 'Dosage', dosagePh: 'e.g. 500mg, 1 tablet',
    timesLabel: 'Times', timesPh: 'e.g. 08:00, 20:00', timesHint: 'Separate each time with a comma',
    activeMeds: 'Active', pausedMeds: 'Paused',
    pause: 'Pause', resume: 'Resume', taken: 'Taken', markTaken: 'Mark taken',
    medSaved: 'Medicine saved', medRemoved: 'Medicine removed',
    errMedName: 'Please enter the medicine name', errTimeFormat: 'Use 24-hour times like 08:00',
    removeMedTitle: 'Remove this medicine?', removeMedBody: 'Its reminder history will be kept.',
    cycleTitle: 'Period tracker', cycleSub: 'Log your cycle to see what comes next',
    logPeriodCta: 'Log period today', periodLogged: 'Period logged',
    nextPeriodIn: 'Next period in', fertileWindowIn: 'Fertile window in',
    avgCycle: 'Average cycle', basedOn: 'Based on', cyclesLower: 'cycles',
    cycleHistory: 'History', ongoing: 'Ongoing',
    noCycles: 'No cycles logged yet', noCyclesSub: 'Log the first day of your period and predictions will appear here.',
    predictionNote: 'Predictions are estimates, not medical advice.',
    tabHabits: 'Habits', tabMore: 'More',
    habitsTitle: 'Daily habits', habitsSub: 'Small things, every day',
    waterTitle: 'Water', glasses: 'glasses', goalLabel: 'Goal', addGlass: 'Add a glass',
    streakLabel: 'day streak', goalMet: 'Goal reached today',
    sleepTitle: 'Sleep', sleepLast: 'Last night', hoursShort: 'h',
    logSleep: 'Log sleep', sleepPh: 'e.g. 7.5',
    weightTitle: 'Weight', kgShort: 'kg', logWeight: 'Log weight',
    bmiLabel: 'BMI', bmiUnderweight: 'Underweight', bmiNormal: 'Normal',
    bmiOverweight: 'Overweight', bmiObese: 'Obese',
    bmiNeedsProfile: 'Add your height in your profile to see BMI',
    waterGoalTitle: 'Daily water goal', habitLogged: 'Logged', goalSaved: 'Goal updated',
    errNumber: 'Please enter a number', timePh: '04:30',
    errTimesNeeded: 'Set both suhoor and iftar times',
    moreTitle: 'More', moreSub: 'Everything else in Imara Afya',
    guidanceTitle: 'Guidance', guidanceSub: 'Health and religious guidance',
    comingSoon: 'Coming soon',
    languageTitle: 'Language', languageSub: 'Choose how the app speaks to you',
    languageChanged: 'Language changed', settingsTitle: 'Settings',
    callFacility: 'Call',
    endPeriodCta: 'Period ended today', periodEnded: 'Period marked as finished',
    periodOngoing: 'Period in progress', startedOn: 'Started', dayCount: 'day', dayCountPlural: 'days',
    avgPeriod: 'Period length', editCycle: 'Edit period',
    startDateLabel: 'Start date', endDateLabel: 'End date', datePh: 'YYYY-MM-DD',
    stillOngoing: 'Still ongoing', markFinished: 'Mark finished',
    cycleSaved: 'Period updated', cycleRemoved: 'Period removed',
    removeCycleTitle: 'Remove this period?', removeCycleBody: 'It will no longer count towards your predictions.',
    errDateFormat: 'Use the format YYYY-MM-DD',
    calendarTitle: 'Calendar', chartTitle: 'Cycle length',
    legendPeriod: 'Period', legendPredicted: 'Predicted', legendFertile: 'Fertile',
    chartNeedsMore: 'Log a few more cycles to see how your cycle length varies.',
    logOnDate: 'Log a period starting', logOnDateBody: 'This will be saved as the first day of your period.',
    confirm: 'Confirm',
    logPeriodAny: 'Log a period', logToday: 'It started today', pickOnCalendar: 'Pick the day below',
    regularityQuestion: 'Is your cycle usually predictable?',
    regularitySub: 'This changes how much the app trusts its own predictions. You can change your answer any time.',
    regularityRegular: 'Yes, it is regular', regularityRegularHint: 'It arrives around the same time each month',
    regularityIrregular: 'No, it varies a lot', regularityIrregularHint: 'The gap changes from month to month',
    regularityUnsure: 'I am not sure', regularityUnsureHint: 'The app will work it out as you log',
    aboutLabel: 'around', confidenceLow: 'Rough estimate', confidenceMedium: 'Getting more accurate',
    lowConfidenceNote: 'Your cycles vary, so this is a rough guide rather than a date to rely on.',
    irregularNote: 'Your cycle length has varied by {days} days. That is common, but if it keeps changing it is worth mentioning to a nurse or doctor.',
    cycleSettings: 'Cycle', changeAnswer: 'Change',
    thisWeek: 'this week', ofGoal: 'of goal', takenToday: 'taken today',
    tapToStart: 'Tap to start', hydration: 'Hydration', nothingDue: 'Nothing due',
    dayShort: 'd', streakShort: 'streak',
    mapView: 'Map', listView: 'List', directions: 'Directions',
    deleteAccountTitle: 'Delete your account?',
    deleteAccountBody: 'This removes everything you have saved in Imara Afya. It cannot be undone and we cannot recover it for you.',
    deleteItemRecords: 'Health records and attachments',
    deleteItemMeds: 'Medicines and dose history',
    deleteItemCycles: 'Cycle and pregnancy tracking',
    deleteItemHabits: 'Water, sleep and weight logs',
    deleteItemAccount: 'Your account and profile',
    deleteNoUndo: 'This is permanent.',
    deleteConfirmPassword: 'Enter your password to confirm',
    deleteKeepAccount: 'Keep my account',
    deleteConfirmCta: 'Delete everything',
    deleteAccountAction: 'Delete account', accountDeleted: 'Your account has been deleted',
  },
  sw: {
    frequencyLabel: 'Mara ngapi?', freqDaily: 'Kila siku', freqAlternate: 'Kila siku ya pili',
    courseEndLabel: 'Hadi (si lazima)', courseEndPh: 'YYYY-MM-DD',
    stockLabel: 'Vidonge vilivyobaki (si lazima)', stockPh: 'mf. 30',
    errCourseDate: 'Andika tarehe ya mwisho kama YYYY-MM-DD',
    errStock: 'Andika vidonge vilivyobaki',
    lateDose: 'umechelewa', missedDose: 'haikutumika',
    adherenceTitle: 'Umetumia kama ilivyoagizwa', lastDaysShort: 'siku 30 zilizopita',
    dosesTaken: 'dozi zimetumika', mostMissed: 'Inayosahaulika zaidi', refillSoon: 'Nunua tena',
    daysLeftShort: 'siku zimebaki', courseEnds: 'Inaisha',
    doseTakenAction: 'Nimemeza', doseSnoozeAction: 'Nikumbushe',
    notifChannelName: 'Vikumbusho vya kila siku',
    tabLog: 'Andika', quickLogTitle: 'Ungependa kuandika nini?',
    logWater: 'Glasi ya maji', logDose: 'Dozi ya dawa',
    waterLogged: 'Maji yameandikwa',
    // ---- dashboard: check-in, routines and the week ----
    energyQuestion: 'Na nguvu zako?', energyHint: 'Umebakiwa na nguvu kiasi gani leo?',
    moodHint: 'Gusa uso unaokufaa',
    back: 'Rudi',
    routineDone: 'Vizuri', routinesAllDone: 'Zote zimekamilika',
    statRoutines: 'Ratiba',
    dailyAverage: 'Wastani wa kila siku', goalDaysMet: 'Lengo limefikiwa',
    medRemindersTitle: 'Vikumbusho vya dawa', medRemindersSub: 'Ukumbusho kila wakati wa dozi',
    medRemindersNone: 'Weka saa kwenye dawa ili upate vikumbusho',
    medReminderTitle: 'Ni wakati wa',
    medRemindersOn: 'Vikumbusho vya dawa vimewashwa', medRemindersOff: 'Vikumbusho vya dawa vimezimwa',
    remindersScheduled: 'vikumbusho kwa siku',
    pregnancyDisclaimer: 'Huu ni mwongozo, si ushauri wa daktari. Hudhuria kliniki zako za ujauzito, na wasiliana na kliniki ikiwa kuna jambo linalokutia wasiwasi.',
    // ---- daily routines ----
    routinesTitle: 'Ratiba za kila siku', routinesSub: 'Mambo madogo uliyoamua kufanya',
    routinesRowSub: 'Jenga tabia zinazolingana na siku yako',
    addRoutine: 'Ongeza ratiba', editRoutine: 'Hariri ratiba',
    routineName: 'Ni nini?', routineNamePh: 'mf. Matembezi ya asubuhi',
    routineDays: 'Siku zipi?', everyDay: 'Kila siku',
    routineTime: 'Saa (si lazima)',
    noRoutinesToday: 'Hakuna cha leo', noRoutinesTodaySub: 'Ongeza ratiba nayo itaonekana hapa.',
    routineSaved: 'Ratiba imehifadhiwa', routineRemoved: 'Ratiba imeondolewa',
    removeRoutineTitle: 'Ondoa ratiba hii?',
    removeRoutineBody: 'Historia yake itaondolewa pia. Haiwezi kurudishwa.',
    allRoutines: 'Ratiba zote', archived: 'Zimesimamishwa',
    doneToday: 'zimefanyika leo',
    errRoutineName: 'Ipe ratiba jina',
    dayMon: 'Jtat', dayTue: 'Jnne', dayWed: 'Jtano', dayThu: 'Alh', dayFri: 'Ijm', daySat: 'Jmos', daySun: 'Jpil',
    // ---- daily check-in ----
    checkInTitle: 'Hali ya leo', checkInSub: 'Unajisikiaje leo?',
    checkInRowSub: 'Hisia na nguvu, kwa sekunde tano',
    moodLabel: 'Hisia', energyLabel: 'Nguvu',
    checkInNote: 'Kuna la kuongeza? (si lazima)', checkInNotePh: 'mf. sikulala vizuri, kichwa kinauma',
    checkInSaved: 'Imehifadhiwa', checkInToday: 'Umejaza leo',
    checkInEdit: 'Badilisha',
    dayStreak: 'siku mfululizo', avgMood: 'Wastani wa hisia', avgEnergy: 'Wastani wa nguvu',
    lastDays: 'Siku 14 zilizopita', noCheckIns: 'Bado hakuna kumbukumbu',
    mood1: 'Mbaya sana', mood2: 'Chini', mood3: 'Sawa', mood4: 'Nzuri', mood5: 'Nzuri sana',
    energy1: 'Nimechoka sana', energy2: 'Nimechoka', energy3: 'Sawa', energy4: 'Nina nguvu', energy5: 'Nimejaa nguvu',
    // ---- pregnancy ----
    pregnancyTitle: 'Ujauzito', pregnancySub: 'Fuatilia wiki na tarehe ya kujifungua',
    pregnancyRowSub: 'Wiki, robo na tarehe ya kujifungua',
    startPregnancy: 'Anza kufuatilia', lastPeriodLabel: 'Siku ya kwanza ya hedhi yako ya mwisho',
    pregnancyNote: 'Dokezo (si lazima)', pregnancyNotePh: 'Chochote unachotaka kukumbuka',
    weeksPregnant: 'wiki', trimesterLabel: 'Robo', dueDateLabel: 'Tarehe ya kujifungua',
    overdueLabel: 'Tarehe imepita',
    endPregnancy: 'Maliza kufuatilia', endPregnancyTitle: 'Funga kumbukumbu hii?',
    endPregnancyBody: 'Unaweza kuongeza dokezo. Kumbukumbu yako itabaki kwenye historia.',
    outcomeLabel: 'Matokeo (si lazima)',
    pregnancyStarted: 'Ufuatiliaji umeanza', pregnancyUpdated: 'Imesasishwa', pregnancyEnded: 'Kumbukumbu imefungwa',
    pastPregnancies: 'Kumbukumbu za zamani', noPregnancy: 'Hufuatilii ujauzito',
    noPregnancySub: 'Anza ukiwa tayari. Unaweza kusimamisha wakati wowote.',
    errLastPeriod: 'Weka tarehe kwa mpangilio wa MWAKA-MWEZI-SIKU',
    // ---- attachments ----
    attachments: 'Viambatisho', addAttachment: 'Ongeza picha',
    attachmentAdded: 'Picha imeambatishwa', attachmentRemoved: 'Picha imeondolewa',
    removeAttachmentTitle: 'Ondoa picha hii?',
    errUploadNotSet: 'Upakiaji wa picha bado haujawekwa.',
    errMediaPermission: 'Ruhusu ufikiaji wa picha ili kuambatisha.',
    // ---- settings screen ----
    settingsSub: 'Vikumbusho, lugha na muonekano wa programu',
    settingsRowSub: 'Arifa, lugha, muonekano',
    appearanceTitle: 'Muonekano', appearanceSub: 'Hufuata simu yako hadi ubadilishe',
    darkMode: 'Hali ya giza',
    unitsTitle: 'Vipimo', unitsSub: 'Jinsi uzito na urefu vinavyoonyeshwa',
    unitsMetric: 'Metriki (kg, cm)', unitsImperial: 'Imperial (lb, in)',
    unitsChanged: 'Vipimo vimebadilishwa',
    accountSection: 'Akaunti', appSection: 'Programu',
    // ---- password reset ----
    forgotTitle: 'Weka upya nywila yako', forgotSub: 'Tutakutumia kiungo cha kuweka nywila mpya.',
    sendResetLink: 'Tuma kiungo',
    checkInbox: 'Angalia barua pepe yako', checkInboxSub: 'Kama anwani hiyo ina akaunti, kiungo kinakuja.',
    resetLinkHint: 'Fungua kiungo kwenye simu hii ili kuweka nywila mpya. Kinaisha baada ya dakika 30.',
    enterCodeInstead: 'Weka msimbo badala yake',
    rememberedIt: 'Umeikumbuka?',
    resetTitle: 'Weka nywila mpya',
    resetSubLink: 'Chagua nywila mpya ya akaunti yako.',
    resetSubCode: 'Weka msimbo kutoka barua pepe yako, kisha chagua nywila mpya.',
    resetCode: 'Msimbo', resetCodePh: 'mf. 7D8H5X4K',
    errCodeFormat: 'Msimbo unapaswa kuwa herufi 8 kutoka barua pepe yako',
    passwordResetDone: 'Nywila imewekwa upya',
    // ---- daily reminders ----
    notifTitle: 'Vikumbusho vya kila siku', notifSub: 'Maji, na ujumbe wa kukujali',
    notifOn: 'Vikumbusho vimewashwa', notifOff: 'Vikumbusho vimezimwa',
    notifDenied: 'Arifa zimezimwa katika mipangilio ya simu yako.',
    notifWaterTitle: 'Wakati wa maji',
    notifWaterBody: 'Glasi moja sasa itakusaidia. Hata funda ndogo zinahesabika.',
    notifCareTitle: 'Habari yako leo?',
    notifCareBody: 'Jipe muda kidogo. Unafanya vizuri kuliko unavyofikiri.',
    // ---- change password ----
    changePasswordTitle: 'Badilisha nywila', changePasswordSub: 'Sasisha nywila unayotumia kuingia',
    currentPassword: 'Nywila ya sasa', newPassword: 'Nywila mpya',
    confirmPassword: 'Thibitisha nywila mpya',
    passwordChanged: 'Nywila imebadilishwa',
    errPasswordMismatch: 'Nywila mpya hazilingani',
    errSamePassword: 'Chagua nywila tofauti na ya sasa',
    attemptsLeft: 'majaribio yamesalia',
    forgotCurrent: 'Umesahau nywila yako?',
    useResetInstead: 'Majaribio mengi mno. Weka upya kwa barua pepe.',
    resetByEmail: 'Weka upya kwa barua pepe',
    resetSent: 'Kama anwani hiyo imesajiliwa, kiungo cha kuweka upya kinakuja.',
    welcomeBack: 'Karibu tena',
    loginSub: 'Ingia ili kuendeleza afya yako.',
    createAccount: 'Fungua akaunti',
    signupSub: 'Anza safari yako ya afya bora.',
    name: 'Jina kamili', namePh: 'mf. Jina Lako',
    email: 'Barua pepe', emailPh: 'wewe@mfano.com',
    password: 'Nywila', passwordPh: '••••••••',
    create: 'Fungua akaunti', login: 'Ingia',
    forgot: 'Umesahau nywila?',
    remember: 'Nikumbuke',
    noAccount: 'Huna akaunti?', haveAccount: 'Una akaunti tayari?',
    signup: 'Jisajili', loginLink: 'Ingia',
    continueWith: 'au endelea na',
    terms: 'Nakubali Masharti na Sera ya Faragha',
    errEmail: 'Weka barua pepe sahihi',
    errPwShort: 'Tumia angalau herufi 8',
    errName: 'Tafadhali weka jina lako',
    errTerms: 'Tafadhali kubali masharti ili kuendelea',
    errGeneric: 'Hitilafu imetokea. Tafadhali jaribu tena.',
    errSocialUnavailable: 'Njia hii ya kuingia haipatikani bado. Tafadhali tumia barua pepe.',
    weak: 'Dhaifu', fair: 'Wastani', good: 'Nzuri', strong: 'Imara',
    successTitle: 'Uko tayari!', successLoginTitle: 'Karibu tena!',
    successSub: 'Tunakupeleka kwenye dashibodi yako ya afya…',
    tagline: 'Afya yako, kwa urahisi.',
    verifyTitle: 'Thibitisha barua pepe yako',
    verifySub: 'Weka nambari ya tarakimu 6 tuliyotuma kwa',
    verifyCta: 'Thibitisha', resend: 'Tuma tena nambari', resendIn: 'Tuma tena baada ya',
    noCode: 'Hukupata nambari?',
    codeErr: 'Nambari si sahihi. Jaribu tena.',
    verifiedTitle: 'Barua pepe imethibitishwa!', verifiedSub: 'Sasa tusanidi wasifu wako…',
    profileTitle: 'Sanidi wasifu wako',
    profileSub: 'Maelezo machache ili kuboresha huduma yako.',
    addPhoto: 'Ongeza picha', changePhoto: 'Badilisha picha',
    genderLabel: 'Jinsia', genderFemale: 'Mwanamke', genderMale: 'Mwanaume', genderOther: 'Nyingine',
    genderWoman: 'Mwanamke', genderMan: 'Mwanaume', errGender: 'Tafadhali chagua jinsia yako',
    heightLabel: 'Urefu (cm)', heightPh: 'mf. 170',
    weightLabel: 'Uzito (kg)', weightPh: 'mf. 65',
    finish: 'Maliza usanidi', skip: 'Ruka kwa sasa', optional: 'Si lazima',
    profileSaved: 'Wasifu umehifadhiwa',
    home: 'Nyumbani', signOut: 'Toka',
    goodMorning: 'Habari ya asubuhi', goodAfternoon: 'Habari ya mchana', goodEvening: 'Habari ya jioni',
    quickActions: 'Vitendo vya haraka', viewAll: 'Ona vyote',
    statRecords: 'Kumbukumbu', statMedsDue: 'Dawa leo', statNextPeriod: 'Hedhi ijayo',
    daysShort: 'siku', daysToGo: 'siku zimebaki',
    healthRecords: 'Kumbukumbu za afya', savedLower: 'zimehifadhiwa', addFirstRecord: 'Ongeza ya kwanza',
    medications: 'Dawa', dueToday: 'za leo', allDone: 'Umemaliza leo',
    periodTracker: 'Kufuatilia hedhi', trackWellness: 'Fuatilia mzunguko wako',
    myProfile: 'Wasifu wangu', planFree: 'Mpango wa bure', planPremium: 'Mpango wa premium',
    medicationsToday: 'Dawa za leo', noMedications: 'Hakuna dawa bado',
    doseLogged: 'Dozi imerekodiwa',
    firstNameLabel: 'Jina la kwanza', lastNameLabel: 'Jina la ukoo', saveChanges: 'Hifadhi mabadiliko',
    recordsTitle: 'Kumbukumbu za afya', recordsSub: 'Magonjwa, mzio na dawa unazohifadhi',
    addRecord: 'Ongeza kumbukumbu', editRecord: 'Hariri kumbukumbu', newRecord: 'Kumbukumbu mpya',
    recordTypeLabel: 'Aina', recordNameLabel: 'Jina', recordNamePh: 'mf. Pumu',
    recordNoteLabel: 'Maelezo', recordNotePh: 'Chochote cha kukumbuka (si lazima)',
    typeCondition: 'Ugonjwa', typeAllergy: 'Mzio', typeMedication: 'Dawa',
    filterAll: 'Zote',
    noRecords: 'Hakuna kumbukumbu bado', noRecordsSub: 'Ongeza magonjwa, mzio na dawa zako ili ziwe nawe kila wakati.',
    recordSaved: 'Kumbukumbu imehifadhiwa', recordRemoved: 'Kumbukumbu imeondolewa',
    errRecordName: 'Tafadhali weka jina',
    removeRecordTitle: 'Ondoa kumbukumbu hii?', removeRecordBody: 'Haiwezi kurudishwa.',
    cancel: 'Ghairi', remove: 'Ondoa', save: 'Hifadhi',
    tabHome: 'Nyumbani', tabRecords: 'Kumbukumbu', tabMeds: 'Dawa', tabCycle: 'Mzunguko', tabProfile: 'Wasifu',
    medsTitle: 'Dawa', medsSub: 'Unachotumia, na lini',
    addMedication: 'Ongeza dawa', editMedication: 'Hariri dawa', newMedication: 'Dawa mpya',
    medNameLabel: 'Dawa', medNamePh: 'mf. Paracetamol',
    dosageLabel: 'Kipimo', dosagePh: 'mf. 500mg, kidonge 1',
    timesLabel: 'Nyakati', timesPh: 'mf. 08:00, 20:00', timesHint: 'Tenganisha kila saa kwa koma',
    activeMeds: 'Zinazotumika', pausedMeds: 'Zimesimamishwa',
    pause: 'Simamisha', resume: 'Endelea', taken: 'Imetumika', markTaken: 'Weka imetumika',
    medSaved: 'Dawa imehifadhiwa', medRemoved: 'Dawa imeondolewa',
    errMedName: 'Tafadhali weka jina la dawa', errTimeFormat: 'Tumia saa za 24 kama 08:00',
    removeMedTitle: 'Ondoa dawa hii?', removeMedBody: 'Historia ya vikumbusho itabaki.',
    cycleTitle: 'Kifuatiliaji cha hedhi', cycleSub: 'Weka mzunguko wako uone kinachofuata',
    logPeriodCta: 'Weka hedhi ya leo', periodLogged: 'Hedhi imewekwa',
    nextPeriodIn: 'Hedhi ijayo baada ya', fertileWindowIn: 'Kipindi cha uzazi baada ya',
    avgCycle: 'Wastani wa mzunguko', basedOn: 'Kwa msingi wa', cyclesLower: 'mizunguko',
    cycleHistory: 'Historia', ongoing: 'Inaendelea',
    noCycles: 'Hakuna mizunguko bado', noCyclesSub: 'Weka siku ya kwanza ya hedhi yako na utabiri utaonekana hapa.',
    predictionNote: 'Utabiri ni makadirio, si ushauri wa daktari.',
    tabHabits: 'Mazoea', tabMore: 'Zaidi',
    habitsTitle: 'Mazoea ya kila siku', habitsSub: 'Mambo madogo, kila siku',
    waterTitle: 'Maji', glasses: 'vikombe', goalLabel: 'Lengo', addGlass: 'Ongeza kikombe',
    streakLabel: 'siku mfululizo', goalMet: 'Lengo limefikiwa leo',
    sleepTitle: 'Usingizi', sleepLast: 'Usiku uliopita', hoursShort: 'saa',
    logSleep: 'Weka usingizi', sleepPh: 'mf. 7.5',
    weightTitle: 'Uzito', kgShort: 'kg', logWeight: 'Weka uzito',
    bmiLabel: 'BMI', bmiUnderweight: 'Uzito mdogo', bmiNormal: 'Kawaida',
    bmiOverweight: 'Uzito zaidi', bmiObese: 'Unene uliopitiliza',
    bmiNeedsProfile: 'Weka urefu wako kwenye wasifu ili kuona BMI',
    waterGoalTitle: 'Lengo la maji kwa siku', habitLogged: 'Imewekwa', goalSaved: 'Lengo limebadilishwa',
    errNumber: 'Tafadhali weka namba', timePh: '04:30',
    errTimesNeeded: 'Weka saa za daku na futari',
    moreTitle: 'Zaidi', moreSub: 'Kila kitu kingine katika Imara Afya',
    guidanceTitle: 'Mwongozo', guidanceSub: 'Mwongozo wa afya na dini',
    comingSoon: 'Inakuja hivi karibuni',
    languageTitle: 'Lugha', languageSub: 'Chagua lugha ya programu',
    languageChanged: 'Lugha imebadilishwa', settingsTitle: 'Mipangilio',
    callFacility: 'Piga simu',
    endPeriodCta: 'Hedhi imeisha leo', periodEnded: 'Hedhi imewekwa kuwa imeisha',
    periodOngoing: 'Hedhi inaendelea', startedOn: 'Ilianza', dayCount: 'siku', dayCountPlural: 'siku',
    avgPeriod: 'Muda wa hedhi', editCycle: 'Hariri hedhi',
    startDateLabel: 'Tarehe ya kuanza', endDateLabel: 'Tarehe ya mwisho', datePh: 'MWAKA-MWEZI-SIKU',
    stillOngoing: 'Bado inaendelea', markFinished: 'Weka imeisha',
    cycleSaved: 'Hedhi imesasishwa', cycleRemoved: 'Hedhi imeondolewa',
    removeCycleTitle: 'Ondoa hedhi hii?', removeCycleBody: 'Haitahesabiwa tena katika utabiri wako.',
    errDateFormat: 'Tumia muundo YYYY-MM-DD',
    calendarTitle: 'Kalenda', chartTitle: 'Urefu wa mzunguko',
    legendPeriod: 'Hedhi', legendPredicted: 'Inatarajiwa', legendFertile: 'Uzazi',
    chartNeedsMore: 'Weka mizunguko michache zaidi ili kuona jinsi urefu wake unavyobadilika.',
    logOnDate: 'Weka hedhi iliyoanza', logOnDateBody: 'Hii itahifadhiwa kama siku ya kwanza ya hedhi yako.',
    confirm: 'Thibitisha',
    logPeriodAny: 'Weka hedhi', logToday: 'Ilianza leo', pickOnCalendar: 'Chagua siku hapa chini',
    regularityQuestion: 'Je, mzunguko wako hutabirika?',
    regularitySub: 'Hii hubadilisha kiasi programu inavyoamini utabiri wake. Unaweza kubadilisha jibu wakati wowote.',
    regularityRegular: 'Ndiyo, ni wa kawaida', regularityRegularHint: 'Huja karibu wakati uleule kila mwezi',
    regularityIrregular: 'Hapana, hubadilika sana', regularityIrregularHint: 'Muda hubadilika kila mwezi',
    regularityUnsure: 'Sina uhakika', regularityUnsureHint: 'Programu itagundua unapoweka taarifa',
    aboutLabel: 'takriban', confidenceLow: 'Makadirio', confidenceMedium: 'Inazidi kuwa sahihi',
    lowConfidenceNote: 'Mizunguko yako hubadilika, hivyo hii ni mwongozo tu, si tarehe ya kutegemea.',
    irregularNote: 'Urefu wa mzunguko wako umebadilika kwa siku {days}. Ni jambo la kawaida, lakini likiendelea ni vyema kumweleza muuguzi au daktari.',
    cycleSettings: 'Mzunguko', changeAnswer: 'Badilisha',
    thisWeek: 'wiki hii', ofGoal: 'ya lengo', takenToday: 'zimetumika leo',
    tapToStart: 'Gusa kuanza', hydration: 'Unywaji maji', nothingDue: 'Hakuna inayohitajika',
    dayShort: 'si', streakShort: 'mfululizo',
    mapView: 'Ramani', listView: 'Orodha', directions: 'Maelekezo',
    deleteAccountTitle: 'Futa akaunti yako?',
    deleteAccountBody: 'Hii itaondoa kila kitu ulichohifadhi katika Imara Afya. Haiwezi kurudishwa na hatuwezi kukurudishia.',
    deleteItemRecords: 'Kumbukumbu za afya na viambatisho',
    deleteItemMeds: 'Dawa na historia ya matumizi',
    deleteItemCycles: 'Ufuatiliaji wa hedhi na ujauzito',
    deleteItemHabits: 'Kumbukumbu za maji, usingizi na uzito',
    deleteItemAccount: 'Akaunti na wasifu wako',
    deleteNoUndo: 'Hii ni ya kudumu.',
    deleteConfirmPassword: 'Weka nywila yako kuthibitisha',
    deleteKeepAccount: 'Nataka kuweka akaunti yangu',
    deleteConfirmCta: 'Futa kila kitu',
    deleteAccountAction: 'Futa akaunti', accountDeleted: 'Akaunti yako imefutwa',
  },
  fr: {
    frequencyLabel: 'À quelle fréquence ?', freqDaily: 'Tous les jours', freqAlternate: 'Un jour sur deux',
    courseEndLabel: "Jusqu'au (facultatif)", courseEndPh: 'AAAA-MM-JJ',
    stockLabel: 'Comprimés restants (facultatif)', stockPh: 'ex. 30',
    errCourseDate: 'Entrez la date de fin au format AAAA-MM-JJ',
    errStock: 'Indiquez combien de comprimés restent',
    lateDose: 'en retard', missedDose: 'manquée',
    adherenceTitle: 'Pris comme prescrit', lastDaysShort: '30 derniers jours',
    dosesTaken: 'doses prises', mostMissed: 'Le plus oublié', refillSoon: 'À renouveler',
    daysLeftShort: 'jours restants', courseEnds: 'Se termine',
    doseTakenAction: 'Pris', doseSnoozeAction: 'Plus tard',
    notifChannelName: 'Rappels quotidiens',
    tabLog: 'Noter', quickLogTitle: 'Que voulez-vous noter ?',
    logWater: 'Un verre d\'eau', logDose: 'Une dose de médicament',
    waterLogged: 'Eau enregistrée',
    // ---- dashboard: check-in, routines and the week ----
    energyQuestion: 'Et votre énergie ?', energyHint: 'Combien vous en reste-t-il aujourd\'hui ?',
    moodHint: 'Touchez le visage qui correspond',
    back: 'Retour',
    routineDone: 'Bien joué', routinesAllDone: 'Tout est fait',
    statRoutines: 'Routines',
    dailyAverage: 'Moyenne par jour', goalDaysMet: 'Objectif atteint',
    medRemindersTitle: 'Rappels de médicaments', medRemindersSub: 'Un rappel à chaque heure de prise',
    medRemindersNone: 'Ajoutez des heures à un médicament pour recevoir des rappels',
    medReminderTitle: "C'est l'heure de",
    medRemindersOn: 'Rappels de médicaments activés', medRemindersOff: 'Rappels de médicaments désactivés',
    remindersScheduled: 'rappels par jour',
    pregnancyDisclaimer: "Ceci est un repère, pas un avis médical. Gardez vos rendez-vous prénatals et contactez une clinique si quelque chose vous inquiète.",
    // ---- daily routines ----
    routinesTitle: 'Routines quotidiennes', routinesSub: 'Les petites choses que vous avez décidé de faire',
    routinesRowSub: 'Créez des habitudes adaptées à votre journée',
    addRoutine: 'Ajouter une routine', editRoutine: 'Modifier la routine',
    routineName: "Qu'est-ce que c'est ?", routineNamePh: 'ex. Marche du matin',
    routineDays: 'Quels jours ?', everyDay: 'Tous les jours',
    routineTime: 'Heure (facultatif)',
    noRoutinesToday: "Rien de prévu aujourd'hui", noRoutinesTodaySub: 'Ajoutez une routine et elle apparaîtra ici.',
    routineSaved: 'Routine enregistrée', routineRemoved: 'Routine supprimée',
    removeRoutineTitle: 'Supprimer cette routine ?',
    removeRoutineBody: 'Son historique sera aussi supprimé. Action irréversible.',
    allRoutines: 'Toutes les routines', archived: 'En pause',
    doneToday: "faites aujourd'hui",
    errRoutineName: 'Donnez un nom à la routine',
    dayMon: 'Lun', dayTue: 'Mar', dayWed: 'Mer', dayThu: 'Jeu', dayFri: 'Ven', daySat: 'Sam', daySun: 'Dim',
    // ---- daily check-in ----
    checkInTitle: 'Point du jour', checkInSub: 'Comment vous sentez-vous ?',
    checkInRowSub: 'Humeur et énergie, en cinq secondes',
    moodLabel: 'Humeur', energyLabel: 'Énergie',
    checkInNote: 'Quelque chose à ajouter ? (facultatif)', checkInNotePh: 'ex. mal dormi, mal de tête',
    checkInSaved: 'Enregistré', checkInToday: "Vous avez déjà répondu aujourd'hui",
    checkInEdit: 'Modifier',
    dayStreak: 'jours de suite', avgMood: 'Humeur moyenne', avgEnergy: 'Énergie moyenne',
    lastDays: '14 derniers jours', noCheckIns: 'Aucune entrée pour le moment',
    mood1: 'Très mal', mood2: 'Bas', mood3: 'Correct', mood4: 'Bien', mood5: 'Très bien',
    energy1: 'Épuisée', energy2: 'Fatiguée', energy3: 'Correct', energy4: 'En forme', energy5: "Pleine d'énergie",
    // ---- pregnancy ----
    pregnancyTitle: 'Grossesse', pregnancySub: 'Suivez vos semaines et votre terme',
    pregnancyRowSub: 'Semaines, trimestre et terme',
    startPregnancy: 'Commencer le suivi', lastPeriodLabel: 'Premier jour de vos dernières règles',
    pregnancyNote: 'Note (facultatif)', pregnancyNotePh: 'Ce que vous voulez retenir',
    weeksPregnant: 'semaines', trimesterLabel: 'Trimestre', dueDateLabel: 'Terme prévu',
    overdueLabel: 'Terme dépassé',
    endPregnancy: 'Terminer le suivi', endPregnancyTitle: 'Clore ce suivi ?',
    endPregnancyBody: "Vous pouvez ajouter une note. Votre dossier reste dans l'historique.",
    outcomeLabel: 'Issue (facultatif)',
    pregnancyStarted: 'Suivi commencé', pregnancyUpdated: 'Mis à jour', pregnancyEnded: 'Suivi clos',
    pastPregnancies: 'Dossiers précédents', noPregnancy: 'Aucun suivi en cours',
    noPregnancySub: 'Commencez quand vous le souhaitez. Vous pouvez arrêter à tout moment.',
    errLastPeriod: 'Saisissez la date au format AAAA-MM-JJ',
    // ---- attachments ----
    attachments: 'Pièces jointes', addAttachment: 'Ajouter une photo',
    attachmentAdded: 'Photo ajoutée', attachmentRemoved: 'Photo supprimée',
    removeAttachmentTitle: 'Supprimer cette photo ?',
    errUploadNotSet: "L'envoi de photos n'est pas encore configuré.",
    errMediaPermission: "Autorisez l'accès aux photos pour en joindre une.",
    // ---- settings screen ----
    settingsSub: "Rappels, langue et apparence de l'application",
    settingsRowSub: 'Notifications, langue, apparence',
    appearanceTitle: 'Apparence', appearanceSub: 'Suit votre téléphone sauf si vous changez',
    darkMode: 'Mode sombre',
    unitsTitle: 'Unités', unitsSub: 'Comment le poids et la taille sont affichés',
    unitsMetric: 'Métrique (kg, cm)', unitsImperial: 'Impérial (lb, in)',
    unitsChanged: 'Unités mises à jour',
    accountSection: 'Compte', appSection: 'Application',
    // ---- password reset ----
    forgotTitle: 'Réinitialiser le mot de passe', forgotSub: 'Nous vous enverrons un lien par e-mail.',
    sendResetLink: 'Envoyer le lien',
    checkInbox: 'Vérifiez votre boîte mail', checkInboxSub: 'Si cette adresse a un compte, le lien arrive.',
    resetLinkHint: 'Ouvrez le lien sur ce téléphone pour choisir un nouveau mot de passe. Il expire dans 30 minutes.',
    enterCodeInstead: 'Saisir le code à la place',
    rememberedIt: 'Vous vous en souvenez ?',
    resetTitle: 'Nouveau mot de passe',
    resetSubLink: 'Choisissez un nouveau mot de passe pour votre compte.',
    resetSubCode: 'Saisissez le code reçu par e-mail, puis choisissez un nouveau mot de passe.',
    resetCode: 'Code de réinitialisation', resetCodePh: 'ex. 7D8H5X4K',
    errCodeFormat: 'Ce code doit comporter 8 caractères, reçus par e-mail',
    passwordResetDone: 'Mot de passe réinitialisé',
    // ---- daily reminders ----
    notifTitle: 'Rappels quotidiens', notifSub: "De l'eau, et un mot pour vous",
    notifOn: 'Rappels activés', notifOff: 'Rappels désactivés',
    notifDenied: 'Les notifications sont désactivées dans les réglages de votre téléphone.',
    notifWaterTitle: "C'est l'heure de boire",
    notifWaterBody: 'Un verre maintenant vous fera du bien. Même quelques gorgées comptent.',
    notifCareTitle: 'Comment allez-vous aujourd’hui ?',
    notifCareBody: 'Prenez un instant pour vous. Vous faites mieux que vous ne le pensez.',
    // ---- change password ----
    changePasswordTitle: 'Changer le mot de passe', changePasswordSub: 'Modifiez le mot de passe de connexion',
    currentPassword: 'Mot de passe actuel', newPassword: 'Nouveau mot de passe',
    confirmPassword: 'Confirmer le nouveau mot de passe',
    passwordChanged: 'Mot de passe modifié',
    errPasswordMismatch: 'Les nouveaux mots de passe ne correspondent pas',
    errSamePassword: 'Choisissez un mot de passe différent de l’actuel',
    attemptsLeft: 'tentatives restantes',
    forgotCurrent: 'Mot de passe oublié ?',
    useResetInstead: 'Trop de tentatives. Réinitialisez par e-mail.',
    resetByEmail: 'Réinitialiser par e-mail',
    resetSent: 'Si cette adresse est enregistrée, un lien de réinitialisation arrive.',
    welcomeBack: 'Bon retour',
    loginSub: 'Connectez-vous pour suivre votre santé.',
    createAccount: 'Créer un compte',
    signupSub: 'Commencez votre parcours vers une meilleure santé.',
    name: 'Nom complet', namePh: 'ex. Non complet',
    email: 'E-mail', emailPh: 'vous@exemple.com',
    password: 'Mot de passe', passwordPh: '••••••••',
    create: 'Créer un compte', login: 'Se connecter',
    forgot: 'Mot de passe oublié ?',
    remember: 'Se souvenir de moi',
    noAccount: 'Vous n’avez pas de compte ?', haveAccount: 'Vous avez déjà un compte ?',
    signup: 'S’inscrire', loginLink: 'Se connecter',
    continueWith: 'ou continuer avec',
    terms: 'J’accepte les Conditions et la Politique de confidentialité',
    errEmail: 'Saisissez une adresse e-mail valide',
    errPwShort: 'Utilisez au moins 8 caractères',
    errName: 'Veuillez saisir votre nom',
    errTerms: 'Veuillez accepter les conditions pour continuer',
    errGeneric: 'Une erreur s’est produite. Veuillez réessayer.',
    errSocialUnavailable: 'Cette option de connexion n’est pas encore disponible. Utilisez l’e-mail.',
    weak: 'Faible', fair: 'Moyen', good: 'Bon', strong: 'Fort',
    successTitle: 'Tout est prêt !', successLoginTitle: 'Bon retour !',
    successSub: 'Redirection vers votre tableau de bord santé…',
    tagline: 'Votre santé, en toute simplicité.',
    verifyTitle: 'Vérifiez votre e-mail',
    verifySub: 'Saisissez le code à 6 chiffres envoyé à',
    verifyCta: 'Vérifier', resend: 'Renvoyer le code', resendIn: 'Renvoyer dans',
    noCode: 'Pas reçu de code ?',
    codeErr: 'Code incorrect. Réessayez.',
    verifiedTitle: 'E-mail vérifié !', verifiedSub: 'Configurons votre profil…',
    profileTitle: 'Configurez votre profil',
    profileSub: 'Quelques détails pour personnaliser vos soins.',
    addPhoto: 'Ajouter une photo', changePhoto: 'Changer la photo',
    genderLabel: 'Genre', genderFemale: 'Femme', genderMale: 'Homme', genderOther: 'Autre',
    genderWoman: 'Femme', genderMan: 'Homme', errGender: 'Veuillez sélectionner votre genre',
    heightLabel: 'Taille (cm)', heightPh: 'ex. 170',
    weightLabel: 'Poids (kg)', weightPh: 'ex. 65',
    finish: 'Terminer', skip: 'Ignorer pour l’instant', optional: 'Facultatif',
    profileSaved: 'Profil enregistré',
    home: 'Accueil', signOut: 'Se déconnecter',
    goodMorning: 'Bonjour', goodAfternoon: 'Bon après-midi', goodEvening: 'Bonsoir',
    quickActions: 'Actions rapides', viewAll: 'Tout voir',
    statRecords: 'Dossiers', statMedsDue: 'Médicaments', statNextPeriod: 'Prochaines règles',
    daysShort: 'j', daysToGo: 'jours restants',
    healthRecords: 'Dossier santé', savedLower: 'enregistrés', addFirstRecord: 'Ajoutez le premier',
    medications: 'Médicaments', dueToday: "aujourd'hui", allDone: 'Terminé pour aujourd’hui',
    periodTracker: 'Suivi des règles', trackWellness: 'Suivez votre cycle',
    myProfile: 'Mon profil', planFree: 'Formule gratuite', planPremium: 'Formule premium',
    medicationsToday: 'Médicaments du jour', noMedications: 'Aucun médicament',
    doseLogged: 'Dose enregistrée',
    firstNameLabel: 'Prénom', lastNameLabel: 'Nom', saveChanges: 'Enregistrer',
    recordsTitle: 'Dossier santé', recordsSub: 'Maladies, allergies et médicaments que vous conservez',
    addRecord: 'Ajouter', editRecord: 'Modifier', newRecord: 'Nouvelle entrée',
    recordTypeLabel: 'Type', recordNameLabel: 'Nom', recordNamePh: 'ex. Asthme',
    recordNoteLabel: 'Note', recordNotePh: 'À retenir (facultatif)',
    typeCondition: 'Maladie', typeAllergy: 'Allergie', typeMedication: 'Médicament',
    filterAll: 'Tout',
    noRecords: 'Aucune entrée', noRecordsSub: 'Ajoutez vos maladies, allergies et médicaments pour les avoir toujours avec vous.',
    recordSaved: 'Entrée enregistrée', recordRemoved: 'Entrée supprimée',
    errRecordName: 'Veuillez saisir un nom',
    removeRecordTitle: 'Supprimer cette entrée ?', removeRecordBody: 'Cette action est irréversible.',
    cancel: 'Annuler', remove: 'Supprimer', save: 'Enregistrer',
    tabHome: 'Accueil', tabRecords: 'Dossier', tabMeds: 'Médicaments', tabCycle: 'Cycle', tabProfile: 'Profil',
    medsTitle: 'Médicaments', medsSub: 'Ce que vous prenez, et quand',
    addMedication: 'Ajouter', editMedication: 'Modifier', newMedication: 'Nouveau médicament',
    medNameLabel: 'Médicament', medNamePh: 'ex. Paracétamol',
    dosageLabel: 'Dose', dosagePh: 'ex. 500mg, 1 comprimé',
    timesLabel: 'Horaires', timesPh: 'ex. 08:00, 20:00', timesHint: 'Séparez chaque heure par une virgule',
    activeMeds: 'Actifs', pausedMeds: 'En pause',
    pause: 'Mettre en pause', resume: 'Reprendre', taken: 'Pris', markTaken: 'Marquer pris',
    medSaved: 'Médicament enregistré', medRemoved: 'Médicament supprimé',
    errMedName: 'Veuillez saisir le nom du médicament', errTimeFormat: 'Utilisez le format 24h, ex. 08:00',
    removeMedTitle: 'Supprimer ce médicament ?', removeMedBody: 'L’historique des rappels sera conservé.',
    cycleTitle: 'Suivi des règles', cycleSub: 'Enregistrez votre cycle pour voir la suite',
    logPeriodCta: 'Enregistrer aujourd’hui', periodLogged: 'Règles enregistrées',
    nextPeriodIn: 'Prochaines règles dans', fertileWindowIn: 'Fenêtre fertile dans',
    avgCycle: 'Cycle moyen', basedOn: 'Basé sur', cyclesLower: 'cycles',
    cycleHistory: 'Historique', ongoing: 'En cours',
    noCycles: 'Aucun cycle enregistré', noCyclesSub: 'Enregistrez le premier jour de vos règles et les prévisions apparaîtront ici.',
    predictionNote: 'Les prévisions sont des estimations, pas un avis médical.',
    tabHabits: 'Habitudes', tabMore: 'Plus',
    habitsTitle: 'Habitudes du jour', habitsSub: 'De petites choses, chaque jour',
    waterTitle: 'Eau', glasses: 'verres', goalLabel: 'Objectif', addGlass: 'Ajouter un verre',
    streakLabel: 'jours de suite', goalMet: 'Objectif atteint aujourd’hui',
    sleepTitle: 'Sommeil', sleepLast: 'La nuit dernière', hoursShort: 'h',
    logSleep: 'Enregistrer', sleepPh: 'ex. 7.5',
    weightTitle: 'Poids', kgShort: 'kg', logWeight: 'Enregistrer',
    bmiLabel: 'IMC', bmiUnderweight: 'Insuffisance pondérale', bmiNormal: 'Normal',
    bmiOverweight: 'Surpoids', bmiObese: 'Obésité',
    bmiNeedsProfile: 'Ajoutez votre taille dans le profil pour voir l’IMC',
    waterGoalTitle: 'Objectif d’eau quotidien', habitLogged: 'Enregistré', goalSaved: 'Objectif mis à jour',
    errNumber: 'Veuillez saisir un nombre', timePh: '04:30',
    errTimesNeeded: 'Renseignez le suhoor et l’iftar',
    moreTitle: 'Plus', moreSub: 'Tout le reste dans Imara Afya',
    guidanceTitle: 'Conseils', guidanceSub: 'Conseils santé et religieux',
    comingSoon: 'Bientôt disponible',
    languageTitle: 'Langue', languageSub: 'Choisissez la langue de l’application',
    languageChanged: 'Langue modifiée', settingsTitle: 'Paramètres',
    callFacility: 'Appeler',
    endPeriodCta: 'Règles terminées aujourd’hui', periodEnded: 'Règles marquées comme terminées',
    periodOngoing: 'Règles en cours', startedOn: 'Début', dayCount: 'jour', dayCountPlural: 'jours',
    avgPeriod: 'Durée des règles', editCycle: 'Modifier',
    startDateLabel: 'Date de début', endDateLabel: 'Date de fin', datePh: 'AAAA-MM-JJ',
    stillOngoing: 'Toujours en cours', markFinished: 'Marquer terminé',
    cycleSaved: 'Règles mises à jour', cycleRemoved: 'Règles supprimées',
    removeCycleTitle: 'Supprimer ces règles ?', removeCycleBody: 'Elles ne compteront plus dans vos prévisions.',
    errDateFormat: 'Utilisez le format AAAA-MM-JJ',
    calendarTitle: 'Calendrier', chartTitle: 'Durée du cycle',
    legendPeriod: 'Règles', legendPredicted: 'Prévu', legendFertile: 'Fertile',
    chartNeedsMore: 'Enregistrez quelques cycles de plus pour voir comment leur durée varie.',
    logOnDate: 'Enregistrer des règles commençant le', logOnDateBody: 'Ce sera enregistré comme le premier jour de vos règles.',
    confirm: 'Confirmer',
    logPeriodAny: 'Enregistrer des règles', logToday: 'Elles ont commencé aujourd’hui', pickOnCalendar: 'Choisissez le jour ci-dessous',
    regularityQuestion: 'Votre cycle est-il généralement régulier ?',
    regularitySub: 'Cela change la confiance accordée aux prévisions. Vous pouvez modifier votre réponse à tout moment.',
    regularityRegular: 'Oui, il est régulier', regularityRegularHint: 'Il arrive à peu près au même moment chaque mois',
    regularityIrregular: 'Non, il varie beaucoup', regularityIrregularHint: 'L’écart change d’un mois à l’autre',
    regularityUnsure: 'Je ne sais pas', regularityUnsureHint: 'L’application le déterminera au fil de vos saisies',
    aboutLabel: 'environ', confidenceLow: 'Estimation', confidenceMedium: 'De plus en plus précis',
    lowConfidenceNote: 'Vos cycles sont variables, donc ceci est une indication et non une date sur laquelle compter.',
    irregularNote: 'La durée de votre cycle a varié de {days} jours. C’est courant, mais si cela persiste, parlez-en à un soignant.',
    cycleSettings: 'Cycle', changeAnswer: 'Modifier',
    thisWeek: 'cette semaine', ofGoal: 'de l’objectif', takenToday: 'pris aujourd’hui',
    tapToStart: 'Appuyez pour commencer', hydration: 'Hydratation', nothingDue: 'Rien à prendre',
    dayShort: 'j', streakShort: 'série',
    mapView: 'Carte', listView: 'Liste', directions: 'Itinéraire',
    deleteAccountTitle: 'Supprimer votre compte ?',
    deleteAccountBody: 'Cela supprime tout ce que vous avez enregistré dans Imara Afya. C’est irréversible et nous ne pourrons rien récupérer.',
    deleteItemRecords: 'Dossier santé et pièces jointes',
    deleteItemMeds: 'Médicaments et historique des prises',
    deleteItemCycles: 'Suivi des règles et de la grossesse',
    deleteItemHabits: 'Relevés d’eau, de sommeil et de poids',
    deleteItemAccount: 'Votre compte et votre profil',
    deleteNoUndo: 'Cette action est définitive.',
    deleteConfirmPassword: 'Saisissez votre mot de passe pour confirmer',
    deleteKeepAccount: 'Garder mon compte',
    deleteConfirmCta: 'Tout supprimer',
    deleteAccountAction: 'Supprimer le compte', accountDeleted: 'Votre compte a été supprimé',
  },
  rn: {
    frequencyLabel: 'Kangahe?', freqDaily: 'Buri musi', freqAlternate: 'Umusi ku wundi',
    courseEndLabel: 'Gushika (si ngombwa)', courseEndPh: 'YYYY-MM-DD',
    stockLabel: 'Ibinini bisigaye (si ngombwa)', stockPh: 'nk. 30',
    errCourseDate: 'Andika itariki y\'iherezo nka YYYY-MM-DD',
    errStock: 'Andika ibinini bisigaye',
    lateDose: 'watevye', missedDose: 'ntiwafashe',
    adherenceTitle: 'Wafashe nk\'uko vyategekanijwe', lastDaysShort: 'iminsi 30 iheze',
    dosesTaken: 'imiti yafashwe', mostMissed: 'Ikunda kwibagirwa', refillSoon: 'Gura ibindi',
    daysLeftShort: 'iminsi isigaye', courseEnds: 'Birangira',
    doseTakenAction: 'Narafashe', doseSnoozeAction: 'Unyibutse',
    notifChannelName: 'Ivyibutsa vya buri musi',
    tabLog: 'Andika', quickLogTitle: 'Woshaka kwandika iki?',
    logWater: 'Ikirahuri c\'amazi', logDose: 'Umuti ufatwa',
    waterLogged: 'Amazi yanditswe',
    // ---- dashboard: check-in, routines and the week ----
    energyQuestion: 'Inguvu zawe?', energyHint: 'Usigaranye inguvu zingahe uyu musi?',
    moodHint: 'Kanda mu maso bikubereye',
    back: 'Subira inyuma',
    routineDone: 'Vyiza cane', routinesAllDone: 'Vyose birarangiye',
    statRoutines: 'Imigenzo',
    dailyAverage: 'Impuzandengo ya buri musi', goalDaysMet: 'Intumbero yashitswe',
    medRemindersTitle: 'Ivyibutsa vy’imiti', medRemindersSub: 'Icibutsa kuri buri saha yo kunywa',
    medRemindersNone: 'Shiraho amasaha ku muti kugira uronke ivyibutsa',
    medReminderTitle: 'Ni igihe co gufata',
    medRemindersOn: 'Ivyibutsa vy’imiti birakora', medRemindersOff: 'Ivyibutsa vy’imiti birahagaze',
    remindersScheduled: 'ivyibutsa ku musi',
    pregnancyDisclaimer: 'Ibi ni ubuyobozi, si impanuro ya muganga. Witabe amanama yawe yo kwa muganga, kandi uhamagare ivuriro nihagira ikikuraje ishinga.',
    // ---- daily routines ----
    routinesTitle: 'Imigenzo ya buri musi', routinesSub: 'Utuntu duto wiyemeje gukora',
    routinesRowSub: 'Tsimbataza ingeso zijanye n’umusi wawe',
    addRoutine: 'Ongeramwo umugenzo', editRoutine: 'Hindura umugenzo',
    routineName: 'Ni iki?', routineNamePh: 'nk. Kugenda mu gitondo',
    routineDays: 'Imisi iyihe?', everyDay: 'Buri musi',
    routineTime: 'Isaha (si ngombwa)',
    noRoutinesToday: 'Nta kintu co uyu musi', noRoutinesTodaySub: 'Ongeramwo umugenzo uzoboneka ng’aha.',
    routineSaved: 'Umugenzo wabitswe', routineRemoved: 'Umugenzo wakuwemwo',
    removeRoutineTitle: 'Gukura uyu mugenzo?',
    removeRoutineBody: 'N’akahise kawo kazokurwamwo. Ntibishobora gusubizwa inyuma.',
    allRoutines: 'Imigenzo yose', archived: 'Yahagaritswe',
    doneToday: 'vyakozwe uyu musi',
    errRoutineName: 'Ha umugenzo izina',
    dayMon: 'Mbe', dayTue: 'Kab', dayWed: 'Gtu', dayThu: 'Kan', dayFri: 'Gnd', daySat: 'Gtd', daySun: 'Cum',
    // ---- daily check-in ----
    checkInTitle: 'Ukuntu umeze uyu musi', checkInSub: 'Wumva umeze gute uyu musi?',
    checkInRowSub: 'Ukumva n’inguvu, mu masegonda atanu',
    moodLabel: 'Ukumva', energyLabel: 'Inguvu',
    checkInNote: 'Hari ico wongerako? (si ngombwa)', checkInNotePh: 'nk. sinaryamye neza, umutwe urandya',
    checkInSaved: 'Vyabitswe', checkInToday: 'Wamaze kwuzuza uyu musi',
    checkInEdit: 'Hindura',
    dayStreak: 'imisi ikurikirana', avgMood: 'Impuzandengo y’ukumva', avgEnergy: 'Impuzandengo y’inguvu',
    lastDays: 'Imisi 14 iheze', noCheckIns: 'Nta na kimwe kiraboneka',
    mood1: 'Bibi cane', mood2: 'Hasi', mood3: 'Bisanzwe', mood4: 'Vyiza', mood5: 'Vyiza cane',
    energy1: 'Narushe cane', energy2: 'Narushe', energy3: 'Bisanzwe', energy4: 'Mfise inguvu', energy5: 'Nuzuye inguvu',
    // ---- pregnancy ----
    pregnancyTitle: 'Imbanyi', pregnancySub: 'Kurikirana indwi n’igihe co kwibaruka',
    pregnancyRowSub: 'Indwi, igice n’igihe co kwibaruka',
    startPregnancy: 'Tangura gukurikirana', lastPeriodLabel: 'Umusi wa mbere w’ukwezi kwawe kwa nyuma',
    pregnancyNote: 'Icandiko (si ngombwa)', pregnancyNotePh: 'Ikintu cose ushaka kwibuka',
    weeksPregnant: 'indwi', trimesterLabel: 'Igice', dueDateLabel: 'Igihe co kwibaruka',
    overdueLabel: 'Igihe carengeye',
    endPregnancy: 'Hagarika gukurikirana', endPregnancyTitle: 'Gusozera iki gikurikiranwa?',
    endPregnancyBody: 'Urashobora kwongerako icandiko. Ivyanditswe bisigara mu kahise kawe.',
    outcomeLabel: 'Inyishu (si ngombwa)',
    pregnancyStarted: 'Gukurikirana kwatanguye', pregnancyUpdated: 'Vyahinduwe', pregnancyEnded: 'Vyasozerewe',
    pastPregnancies: 'Ivyahoze', noPregnancy: 'Nta mbanyi ukurikirana',
    noPregnancySub: 'Tangura igihe witeguye. Urashobora guhagarika igihe ico ari co cose.',
    errLastPeriod: 'Andika itariki mu buryo bwa UMWAKA-UKWEZI-UMUSI',
    // ---- attachments ----
    attachments: 'Ivyometsweko', addAttachment: 'Ongeramwo ifoto',
    attachmentAdded: 'Ifoto yometsweko', attachmentRemoved: 'Ifoto yakuwemwo',
    removeAttachmentTitle: 'Gukura iyi foto?',
    errUploadNotSet: 'Kurungika amafoto ntibirashirwaho.',
    errMediaPermission: 'Emerera kwinjira mu mafoto kugira wometseko.',
    // ---- settings screen ----
    settingsSub: 'Ivyibutsa, ururimi n’ukuntu porogarama isa',
    settingsRowSub: 'Ubutumwa, ururimi, isura',
    appearanceTitle: 'Isura', appearanceSub: 'Ikurikira terefone yawe kiretse uhinduye',
    darkMode: 'Uburyo bw’umwijima',
    unitsTitle: 'Ibipimo', unitsSub: 'Ukuntu uburemere n’uburebure byerekanwa',
    unitsMetric: 'Metric (kg, cm)', unitsImperial: 'Imperial (lb, in)',
    unitsChanged: 'Ibipimo vyahinduwe',
    accountSection: 'Konte', appSection: 'Porogarama',
    // ---- password reset ----
    forgotTitle: 'Subiramwo ijambo ry’ibanga', forgotSub: 'Turakurungikira umurongo kuri imeyili yawe.',
    sendResetLink: 'Rungika umurongo',
    checkInbox: 'Raba imeyili yawe', checkInboxSub: 'Iyo adiresi nifise konte, umurongo uraza.',
    resetLinkHint: 'Fungura uwo murongo kuri iyi terefone kugira ushireho ijambo rishasha. Uhera mu minota 30.',
    enterCodeInstead: 'Andika kode aho gukoresha umurongo',
    rememberedIt: 'Wibutse?',
    resetTitle: 'Shiraho ijambo rishasha',
    resetSubLink: 'Hitamwo ijambo ry’ibanga rishasha rya konte yawe.',
    resetSubCode: 'Andika kode wahawe kuri imeyili, uhone uhitemwo ijambo rishasha.',
    resetCode: 'Kode yo gusubiramwo', resetCodePh: 'nk. 7D8H5X4K',
    errCodeFormat: 'Iyo kode ikwiye kuba inyuguti 8 wahawe kuri imeyili',
    passwordResetDone: 'Ijambo ry’ibanga ryasubiwemwo neza',
    // ---- daily reminders ----
    notifTitle: 'Ivyibutsa vya buri musi', notifSub: "Amazi, n'ijambo ryiza kuri wewe",
    notifOn: 'Ivyibutsa birakora', notifOff: 'Ivyibutsa birahagaze',
    notifDenied: 'Ubutumwa bwazimijwe mu mabwirizwa ya terefone yawe.',
    notifWaterTitle: 'Ni igihe co kunywa amazi',
    notifWaterBody: "Ikirahuri kimwe ubu kiragufasha. N'udutonyanga duke turaharurwa.",
    notifCareTitle: 'Umeze gute uyu musi?',
    notifCareBody: 'Fata akanya gato kuri wewe. Uriko urakora neza kuruta uko wibaza.',
    // ---- change password ----
    changePasswordTitle: 'Hindura ijambo ry’ibanga', changePasswordSub: 'Hindura ijambo ry’ibanga winjiza',
    currentPassword: 'Ijambo ry’ibanga ririho', newPassword: 'Ijambo ry’ibanga rishasha',
    confirmPassword: 'Emeza iryo jambo rishasha',
    passwordChanged: 'Ijambo ry’ibanga ryahinduwe',
    errPasswordMismatch: 'Amajambo mashasha ntaranganya',
    errSamePassword: 'Hitamwo iryo ritandukanye n’iririho',
    attemptsLeft: 'ingerageza zisigaye',
    forgotCurrent: 'Wibagiye ijambo ry’ibanga?',
    useResetInstead: 'Wagerageje kenshi cane. Subiramwo ukoresheje imeyili.',
    resetByEmail: 'Subiramwo ukoresheje imeyili',
    resetSent: 'Iyo adiresi niba yanditswe, umurongo wo gusubiramwo uraza.',
    welcomeBack: 'Murakaza neza',
    loginSub: 'Injira kugira ukurikirane amagara yawe.',
    createAccount: 'Fungura konte',
    signupSub: 'Tangura urugendo rwawe rw’amagara meza.',
    name: 'Izina ryuzuye', namePh: 'akarorero Amazin Yawe',
    email: 'Imeyili', emailPh: 'wewe@akarorero.com',
    password: 'Ijambo ry’ibanga', passwordPh: '••••••••',
    create: 'Fungura konte', login: 'Injira',
    forgot: 'Wibagiwe ijambo ry’ibanga?',
    remember: 'Unyibuke',
    noAccount: 'Nta konte ufise?', haveAccount: 'Usanzwe ufise konte?',
    signup: 'Iyandikishe', loginLink: 'Injira',
    continueWith: 'canke winjire ukoresheje',
    terms: 'Ndemera Amabwirizwa n’Ipolitike y’ibanga',
    errEmail: 'Andika imeyili nyayo',
    errPwShort: 'Koresha nibura inyuguti 8',
    errName: 'Andika izina ryawe',
    errTerms: 'Emera amabwirizwa kugira ubandanye',
    errGeneric: 'Habaye ikibazo. Subira ugerageze.',
    errSocialUnavailable: 'Ubu buryo bwo kwinjira ntiburaboneka. Koresha imeyili.',
    weak: 'Ridakomeye', fair: 'Risanzwe', good: 'Ryiza', strong: 'Rikomeye',
    successTitle: 'Vyose birarangiye!', successLoginTitle: 'Murakaza neza!',
    successSub: 'Turiko turakujana ku rupapuro rwawe rw’amagara…',
    tagline: 'Amagara yawe, mu buryo bworoshe.',
    verifyTitle: 'Emeza imeyili yawe',
    verifySub: 'Andika kode y’imibare 6 twakwoherereje kuri',
    verifyCta: 'Emeza', resend: 'Subira wohereze kode', resendIn: 'Subira mu',
    noCode: 'Ntiwakiriye kode?',
    codeErr: 'Iyo kode siyo. Gerageza.',
    verifiedTitle: 'Imeyili yemejwe!', verifiedSub: 'Ubu reka dushireho umwidondoro wawe…',
    profileTitle: 'Shiraho umwidondoro wawe',
    profileSub: 'Amakuru make kugira twongere ubuvuzi bwawe.',
    addPhoto: 'Ongeraho ifoto', changePhoto: 'Hindura ifoto',
    genderLabel: 'Igitsina', genderFemale: 'Umugore', genderMale: 'Umugabo', genderOther: 'Ikindi',
    genderWoman: 'Umugore', genderMan: 'Umugabo', errGender: 'Hitamwo igitsina cawe',
    heightLabel: 'Uburebure (cm)', heightPh: 'akarorero 170',
    weightLabel: 'Ibiro (kg)', weightPh: 'akarorero 65',
    finish: 'Rangiza', skip: 'Simba kuri ubu', optional: 'Si itegeko',
    profileSaved: 'Umwidondoro warabitswe',
    home: 'Ahabanza', signOut: 'Sohoka',
    goodMorning: 'Mwaramutse', goodAfternoon: 'Mwiriwe', goodEvening: 'Mwiriwe',
    quickActions: 'Ibikorwa vyihuta', viewAll: 'Raba vyose',
    statRecords: 'Amakuru', statMedsDue: 'Imiti y’uyu musi', statNextPeriod: 'Imihango itaha',
    daysShort: 'im', daysToGo: 'imisi isigaye',
    healthRecords: 'Amakuru y’amagara', savedLower: 'yabitswe', addFirstRecord: 'Ongeraho aya mbere',
    medications: 'Imiti', dueToday: 'y’uyu musi', allDone: 'Warangije uyu musi',
    periodTracker: 'Gukurikirana imihango', trackWellness: 'Kurikirana imihango yawe',
    myProfile: 'Umwidondoro wanje', planFree: 'Uburyo bw’ubuntu', planPremium: 'Uburyo bwa premium',
    medicationsToday: 'Imiti y’uyu musi', noMedications: 'Nta miti irahari',
    doseLogged: 'Dozi yanditswe',
    firstNameLabel: 'Izina', lastNameLabel: 'Izina ry’umuryango', saveChanges: 'Bika impinduka',
    recordsTitle: 'Amakuru y’amagara', recordsSub: 'Indwara, ivyo utabona n’imiti ubika',
    addRecord: 'Ongeraho', editRecord: 'Hindura', newRecord: 'Ikinyegeza gishasha',
    recordTypeLabel: 'Ubwoko', recordNameLabel: 'Izina', recordNamePh: 'nk. Asima',
    recordNoteLabel: 'Icete', recordNotePh: 'Ico wokwibuka (ntibisabwa)',
    typeCondition: 'Indwara', typeAllergy: 'Aleriji', typeMedication: 'Umuti',
    filterAll: 'Vyose',
    noRecords: 'Nta makuru arahari', noRecordsSub: 'Ongeraho indwara, aleriji n’imiti vyawe kugira ubigumane.',
    recordSaved: 'Vyabitswe', recordRemoved: 'Vyakuweho',
    errRecordName: 'Andika izina',
    removeRecordTitle: 'Ukuraho ivyanditswe?', removeRecordBody: 'Ntibishobora gusubizwa.',
    cancel: 'Reka', remove: 'Kuraho', save: 'Bika',
    tabHome: 'Ahabanza', tabRecords: 'Amakuru', tabMeds: 'Imiti', tabCycle: 'Ukwezi', tabProfile: 'Umwidondoro',
    medsTitle: 'Imiti', medsSub: 'Ivyo unywa, n’igihe',
    addMedication: 'Ongeraho umuti', editMedication: 'Hindura umuti', newMedication: 'Umuti mushasha',
    medNameLabel: 'Umuti', medNamePh: 'nk. Paracetamol',
    dosageLabel: 'Igipimo', dosagePh: 'nk. 500mg, ikinini 1',
    timesLabel: 'Amasaha', timesPh: 'nk. 08:00, 20:00', timesHint: 'Tandukanya amasaha n’aka kama',
    activeMeds: 'Irakoreshwa', pausedMeds: 'Yahagaritswe',
    pause: 'Hagarika', resume: 'Subira', taken: 'Yanyoywe', markTaken: 'Emeza ko wanyoye',
    medSaved: 'Umuti wabitswe', medRemoved: 'Umuti wakuweho',
    errMedName: 'Andika izina ry’umuti', errTimeFormat: 'Koresha amasaha 24 nka 08:00',
    removeMedTitle: 'Ukuraho uyu muti?', removeMedBody: 'Amakuru y’ibibutsa arabikwa.',
    cycleTitle: 'Gukurikirana amaraso', cycleSub: 'Andika ukwezi kwawe urabe ibikurikira',
    logPeriodCta: 'Andika ay’uyu musi', periodLogged: 'Vyanditswe',
    nextPeriodIn: 'Ayakurikira mu', fertileWindowIn: 'Igihe c’uburumbuke mu',
    avgCycle: 'Impuzandengo y’ukwezi', basedOn: 'Bishingiye ku', cyclesLower: 'kwezi',
    cycleHistory: 'Kahise', ongoing: 'Biriko biraba',
    noCycles: 'Nta kwezi kwanditswe', noCyclesSub: 'Andika umusi wa mbere w’amaraso, ivyo biteganijwe bizoboneka ng’aha.',
    predictionNote: 'Ivyo biteganijwe ni ibigereranyo, si impanuro y’umuganga.',
    tabHabits: 'Ingeso', tabMore: 'Ibindi',
    habitsTitle: 'Ingeso za buri musi', habitsSub: 'Utuntu duto, buri musi',
    waterTitle: 'Amazi', glasses: 'ibirahuri', goalLabel: 'Intumbero', addGlass: 'Ongeraho ikirahuri',
    streakLabel: 'imisi ikurikiranye', goalMet: 'Intumbero yashitse uyu musi',
    sleepTitle: 'Itiro', sleepLast: 'Ijoro riheze', hoursShort: 'am',
    logSleep: 'Andika itiro', sleepPh: 'nk. 7.5',
    weightTitle: 'Uburemere', kgShort: 'kg', logWeight: 'Andika uburemere',
    bmiLabel: 'BMI', bmiUnderweight: 'Uburemere buke', bmiNormal: 'Bisanzwe',
    bmiOverweight: 'Uburemere bwinshi', bmiObese: 'Umubyibuho ukabije',
    bmiNeedsProfile: 'Andika uburebure bwawe mu mwidondoro kugira ubone BMI',
    waterGoalTitle: 'Intumbero y’amazi ku musi', habitLogged: 'Vyanditswe', goalSaved: 'Intumbero yahindutse',
    errNumber: 'Andika igiharuro', timePh: '04:30',
    errTimesNeeded: 'Shiraho amasaha ya suhoor na iftar',
    moreTitle: 'Ibindi', moreSub: 'Ibindi vyose muri Imara Afya',
    guidanceTitle: 'Ubuyobozi', guidanceSub: 'Ubuyobozi bw’amagara n’ubw’idini',
    comingSoon: 'Biregereje',
    languageTitle: 'Ururimi', languageSub: 'Hitamwo ururimi rw’ikoraniro',
    languageChanged: 'Ururimi rwarahindutse', settingsTitle: 'Amagenamiterere',
    callFacility: 'Terefona',
    endPeriodCta: 'Amaraso yarangiye uyu musi', periodEnded: 'Vyanditswe ko vyarangiye',
    periodOngoing: 'Amaraso ariko araza', startedOn: 'Vyatanguye', dayCount: 'umusi', dayCountPlural: 'imisi',
    avgPeriod: 'Igihe amaraso amara', editCycle: 'Hindura',
    startDateLabel: 'Itariki vyatangiye', endDateLabel: 'Itariki vyarangiriye', datePh: 'UMWAKA-UKWEZI-UMUSI',
    stillOngoing: 'Biracariko', markFinished: 'Emeza ko vyarangiye',
    cycleSaved: 'Vyahinduwe', cycleRemoved: 'Vyakuweho',
    removeCycleTitle: 'Ukuraho aya maraso?', removeCycleBody: 'Ntibizoba bikibariwe mu vyo biteganijwe.',
    errDateFormat: 'Koresha uburyo YYYY-MM-DD',
    calendarTitle: 'Kalindari', chartTitle: 'Uburebure bw’ukwezi',
    legendPeriod: 'Amaraso', legendPredicted: 'Biteganijwe', legendFertile: 'Uburumbuke',
    chartNeedsMore: 'Andika ukwezi kwinshi kugira ubone ingene uburebure bwako buhinduka.',
    logOnDate: 'Andika amaraso yatanguye', logOnDateBody: 'Uyu uzoba ari umusi wa mbere w’amaraso yawe.',
    confirm: 'Emeza',
    logPeriodAny: 'Andika amaraso', logToday: 'Yatanguye uyu musi', pickOnCalendar: 'Hitamwo umusi hepfo',
    regularityQuestion: 'Ukwezi kwawe kwama kuza ku gihe?',
    regularitySub: 'Ivyo bihindura ukuntu porogaramu yizigira ivyo iteganya. Urashobora guhindura inyishu igihe ico ari co cose.',
    regularityRegular: 'Ego, kurasanzwe', regularityRegularHint: 'Kuza ku gihe kimwe buri kwezi',
    regularityIrregular: 'Oya, birahinduka cane', regularityIrregularHint: 'Ikiringo gihinduka buri kwezi',
    regularityUnsure: 'Sinzi neza', regularityUnsureHint: 'Porogaramu izobimenya uko wandika',
    aboutLabel: 'nka', confidenceLow: 'Igereranyo', confidenceMedium: 'Biriko birarushiriza kuba vyo',
    lowConfidenceNote: 'Ukwezi kwawe kurahinduka, rero ivyo ni ubuyobozi gusa, si itariki wokwizigira.',
    irregularNote: 'Uburebure bw’ukwezi kwawe bwarahindutse imisi {days}. Birasanzwe, ariko bibandanije ni vyiza kubibwira umuforoma canke umuganga.',
    cycleSettings: 'Ukwezi', changeAnswer: 'Hindura',
    thisWeek: 'iyi ndwi', ofGoal: 'ku ntumbero', takenToday: 'yanyoywe uyu musi',
    tapToStart: 'Kanda utangure', hydration: 'Kunywa amazi', nothingDue: 'Nta co usabwa',
    dayShort: 'um', streakShort: 'ikurikirana',
    mapView: 'Ikarata', listView: 'Urutonde', directions: 'Inzira',
    deleteAccountTitle: 'Gusiba konti yawe?',
    deleteAccountBody: 'Ivyo bizokuraho ivyo wabitse vyose muri Imara Afya. Ntibishobora gusubizwa kandi ntitwoshobora kubigarukana.',
    deleteItemRecords: 'Amakuru y’amagara n’ivyometsweko',
    deleteItemMeds: 'Imiti n’akahise k’ukuyinywa',
    deleteItemCycles: 'Gukurikirana amaraso n’imbanyi',
    deleteItemHabits: 'Ivyanditswe vy’amazi, itiro n’uburemere',
    deleteItemAccount: 'Konti n’umwidondoro wawe',
    deleteNoUndo: 'Ivyo ntibisubirwamwo.',
    deleteConfirmPassword: 'Andika ijambo ryawe ry’ibanga wemeze',
    deleteKeepAccount: 'Ngumane konti yanje',
    deleteConfirmCta: 'Siba vyose',
    deleteAccountAction: 'Gusiba konti', accountDeleted: 'Konti yawe yasibwe',
  },
};

export type LangCode = keyof typeof STRINGS;
export type Strings = (typeof STRINGS)['en'];

type LangContextValue = {
  lang: LangCode;
  setLang: React.Dispatch<React.SetStateAction<LangCode>>;
  t: Strings;
};

const LangContext = createContext<LangContextValue | null>(null);

export function LangProvider({
  children,
  initialLang = 'en',
}: {
  children: ReactNode;
  initialLang?: LangCode;
}) {
  const [lang, setLangState] = useState<LangCode>(initialLang);

  // restore the language the user picked last time they used the app
  useEffect(() => {
    let cancelled = false;

    getLang().then((saved) => {
      if (!cancelled && saved && saved in STRINGS) setLangState(saved as LangCode);
    });

    return () => {
      cancelled = true;
    };
  }, []);

  // same signature as useState's setter, but persists whatever it lands on
  const setLang = useCallback<React.Dispatch<React.SetStateAction<LangCode>>>((next) => {
    setLangState((prev) => {
      const resolved = typeof next === 'function' ? (next as (p: LangCode) => LangCode)(prev) : next;
      if (resolved !== prev) saveLang(resolved);
      return resolved;
    });
  }, []);

  const value = useMemo<LangContextValue>(
    () => ({ lang, setLang, t: (STRINGS[lang] || STRINGS.en) as Strings }),
    [lang, setLang],
  );
  return <LangContext.Provider value={value}>{children}</LangContext.Provider>;
}

export function useStrings() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useStrings must be used inside <LangProvider>');
  return ctx;
}
