// constants/strings.tsx — i18n dictionary + language context (EN / SW / FR / RN)
import React, {
  createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode,
} from 'react';

import { getLang, saveLang } from '@/lib/prefs';

// `name` is what each language calls itself — never translated, so a speaker
// can always find their own language in the list.
export const LANGS = [
  { code: 'en', label: 'EN', name: 'English' },
  { code: 'sw', label: 'SW', name: 'Kiswahili' },
  { code: 'fr', label: 'FR', name: 'Français' },
  { code: 'rn', label: 'RN', name: 'Ikirundi' },
] as const;

export const STRINGS = {
  en: {
    welcomeBack: 'Welcome back',
    loginSub: 'Log in to keep your health on track.',
    createAccount: 'Create account',
    signupSub: 'Start your journey to stronger health.',
    name: 'Full name', namePh: 'e.g. Your Name',
    email: 'Email', emailPh: 'you@example.com',
    password: 'Password', passwordPh: '••••••••',
    create: 'Create account', login: 'Log in',
    forgot: 'Forgot password?',
    remember: 'Remember me',
    noAccount: "Don’t have an account?", haveAccount: 'Already have an account?',
    signup: 'Sign up', loginLink: 'Log in',
    continueWith: 'or continue with',
    terms: 'I agree to the Terms & Privacy Policy',
    errEmail: 'Enter a valid email address',
    errPwShort: 'Use at least 8 characters',
    errName: 'Please enter your name',
    errTerms: 'Please accept the terms to continue',
    errGeneric: 'Something went wrong. Please try again.',
    errSocialUnavailable: 'This sign-in option isn’t available yet. Please use email instead.',
    weak: 'Weak', fair: 'Fair', good: 'Good', strong: 'Strong',
    successTitle: 'You’re all set!', successLoginTitle: 'Welcome back!',
    successSub: 'Taking you to your health dashboard…',
    tagline: 'Your health, made simple.',
    verifyTitle: 'Verify your email',
    verifySub: 'Enter the 6-digit code we sent to',
    verifyCta: 'Verify', resend: 'Resend code', resendIn: 'Resend code in',
    noCode: 'Didn’t get a code?',
    codeErr: 'That code isn’t right. Try again.',
    verifiedTitle: 'Email verified!', verifiedSub: 'Now let’s set up your profile…',
    profileTitle: 'Set up your profile',
    profileSub: 'A few details to personalise your care.',
    addPhoto: 'Add a photo', changePhoto: 'Change photo',
    genderLabel: 'Gender', genderFemale: 'Female', genderMale: 'Male', genderOther: 'Other',
    genderWoman: 'Woman', genderMan: 'Man', errGender: 'Please select your gender',
    heightLabel: 'Height (cm)', heightPh: 'e.g. 170',
    weightLabel: 'Weight (kg)', weightPh: 'e.g. 65',
    religionLabel: 'Religion', religionPh: 'Select your religion',
    religions: ['Christianity', 'Islam', 'Hinduism', 'Buddhism', 'Traditional', 'None', 'Prefer not to say'],
    finish: 'Finish setup', skip: 'Skip for now', optional: 'Optional',
    profileSaved: 'Profile saved',
    home: 'Home', signOut: 'Sign out',
    goodMorning: 'Good morning', goodAfternoon: 'Good afternoon', goodEvening: 'Good evening',
    quickActions: 'Quick actions', viewAll: 'View all',
    statRecords: 'Records', statMedsDue: 'Meds due', statNextPeriod: 'Next period',
    daysShort: 'd', daysToGo: 'days to go',
    healthRecords: 'Health records', savedLower: 'saved', addFirstRecord: 'Add your first',
    findCare: 'Find care', clinicsNearYou: 'Clinics near you',
    medications: 'Medications', dueToday: 'due today', allDone: 'All done today',
    periodTracker: 'Period tracker', trackWellness: 'Track your cycle',
    myProfile: 'My profile', planFree: 'Free plan', planPremium: 'Premium plan',
    medicationsToday: 'Medications today', noMedications: 'No medications yet',
    doseLogged: 'Dose logged',
    firstNameLabel: 'First name', lastNameLabel: 'Last name', saveChanges: 'Save changes',
    recordsTitle: 'Health records', recordsSub: 'Conditions, allergies and medicines you keep on file',
    addRecord: 'Add record', editRecord: 'Edit record', newRecord: 'New record',
    recordTypeLabel: 'Type', recordNameLabel: 'Name', recordNamePh: 'e.g. Asthma',
    recordNoteLabel: 'Note', recordNotePh: 'Anything worth remembering (optional)',
    typeCondition: 'Condition', typeAllergy: 'Allergy', typeMedication: 'Medicine',
    filterAll: 'All',
    noRecords: 'No records yet', noRecordsSub: 'Add your conditions, allergies and medicines so they are always with you.',
    recordSaved: 'Record saved', recordRemoved: 'Record removed',
    errRecordName: 'Please enter a name',
    removeRecordTitle: 'Remove this record?', removeRecordBody: 'This cannot be undone.',
    cancel: 'Cancel', remove: 'Remove', save: 'Save',
    tabHome: 'Home', tabRecords: 'Records', tabMeds: 'Meds', tabCycle: 'Cycle', tabProfile: 'Profile',
    medsTitle: 'Medications', medsSub: 'What you take, and when',
    addMedication: 'Add medicine', editMedication: 'Edit medicine', newMedication: 'New medicine',
    medNameLabel: 'Medicine', medNamePh: 'e.g. Paracetamol',
    dosageLabel: 'Dosage', dosagePh: 'e.g. 500mg, 1 tablet',
    timesLabel: 'Times', timesPh: 'e.g. 08:00, 20:00', timesHint: 'Separate each time with a comma',
    activeMeds: 'Active', pausedMeds: 'Paused',
    pause: 'Pause', resume: 'Resume', taken: 'Taken', markTaken: 'Mark taken',
    medSaved: 'Medicine saved', medRemoved: 'Medicine removed',
    errMedName: 'Please enter the medicine name', errTimeFormat: 'Use 24-hour times like 08:00',
    removeMedTitle: 'Remove this medicine?', removeMedBody: 'Its reminder history will be kept.',
    cycleTitle: 'Period tracker', cycleSub: 'Log your cycle to see what comes next',
    logPeriodCta: 'Log period today', periodLogged: 'Period logged',
    nextPeriodIn: 'Next period in', fertileWindowIn: 'Fertile window in',
    avgCycle: 'Average cycle', basedOn: 'Based on', cyclesLower: 'cycles',
    cycleHistory: 'History', ongoing: 'Ongoing',
    noCycles: 'No cycles logged yet', noCyclesSub: 'Log the first day of your period and predictions will appear here.',
    predictionNote: 'Predictions are estimates, not medical advice.',
    tabHabits: 'Habits', tabMore: 'More',
    habitsTitle: 'Daily habits', habitsSub: 'Small things, every day',
    waterTitle: 'Water', glasses: 'glasses', goalLabel: 'Goal', addGlass: 'Add a glass',
    streakLabel: 'day streak', goalMet: 'Goal reached today',
    sleepTitle: 'Sleep', sleepLast: 'Last night', hoursShort: 'h',
    logSleep: 'Log sleep', sleepPh: 'e.g. 7.5',
    weightTitle: 'Weight', kgShort: 'kg', logWeight: 'Log weight',
    bmiLabel: 'BMI', bmiUnderweight: 'Underweight', bmiNormal: 'Normal',
    bmiOverweight: 'Overweight', bmiObese: 'Obese',
    bmiNeedsProfile: 'Add your height in your profile to see BMI',
    waterGoalTitle: 'Daily water goal', habitLogged: 'Logged', goalSaved: 'Goal updated',
    errNumber: 'Please enter a number',
    ramadanTitle: 'Ramadan mode', ramadanSub: 'Shift medicine reminders around your fast',
    ramadanOn: 'Ramadan mode is on', ramadanOff: 'Ramadan mode is off',
    suhoorLabel: 'Suhoor', iftarLabel: 'Iftar', timePh: '04:30',
    ramadanSaved: 'Ramadan settings saved',
    errTimesNeeded: 'Set both suhoor and iftar times',
    errSuhoorOrder: 'Suhoor must come before iftar',
    adjustedTitle: 'Adjusted dose times', originalLabel: 'Normally', adjustedLabel: 'While fasting',
    noShift: 'No dose times need moving', noMedsForRamadan: 'Add your medicines to see adjusted times',
    ramadanDisclaimer:
      'This only reschedules reminders. Ask your doctor or pharmacist before changing when you take any medicine, and before fasting with a health condition.',
    moreTitle: 'More', moreSub: 'Everything else in Imara Afya',
    guidanceTitle: 'Guidance', guidanceSub: 'Health and religious guidance',
    findCareTitle: 'Find care', findCareSub: 'Hospitals and clinics near you',
    comingSoon: 'Coming soon',
    languageTitle: 'Language', languageSub: 'Choose how the app speaks to you',
    languageChanged: 'Language changed', settingsTitle: 'Settings',
    careTitle: 'Find care', careSub: 'Hospitals, clinics and pharmacies',
    searchCarePh: 'Search by name or area',
    typeHospital: 'Hospitals', typeClinic: 'Clinics', typePharmacy: 'Pharmacies',
    callFacility: 'Call', noPhone: 'No phone number',
    noFacilities: 'No facilities listed yet',
    noFacilitiesSub: 'The directory for your area is still being built. Please check back soon.',
    noSearchResults: 'Nothing matched your search',
    emergencyNote: 'In an emergency, go to the nearest hospital straight away.',
    endPeriodCta: 'Period ended today', periodEnded: 'Period marked as finished',
    periodOngoing: 'Period in progress', startedOn: 'Started', dayCount: 'day', dayCountPlural: 'days',
    avgPeriod: 'Period length', editCycle: 'Edit period',
    startDateLabel: 'Start date', endDateLabel: 'End date', datePh: 'YYYY-MM-DD',
    stillOngoing: 'Still ongoing', markFinished: 'Mark finished',
    cycleSaved: 'Period updated', cycleRemoved: 'Period removed',
    removeCycleTitle: 'Remove this period?', removeCycleBody: 'It will no longer count towards your predictions.',
    errDateFormat: 'Use the format YYYY-MM-DD',
    calendarTitle: 'Calendar', chartTitle: 'Cycle length',
    legendPeriod: 'Period', legendPredicted: 'Predicted', legendFertile: 'Fertile',
    chartNeedsMore: 'Log a few more cycles to see how your cycle length varies.',
    logOnDate: 'Log a period starting', logOnDateBody: 'This will be saved as the first day of your period.',
    confirm: 'Confirm',
    logPeriodAny: 'Log a period', logToday: 'It started today', pickOnCalendar: 'Pick the day below',
    regularityQuestion: 'Is your cycle usually predictable?',
    regularitySub: 'This changes how much the app trusts its own predictions. You can change your answer any time.',
    regularityRegular: 'Yes, it is regular', regularityRegularHint: 'It arrives around the same time each month',
    regularityIrregular: 'No, it varies a lot', regularityIrregularHint: 'The gap changes from month to month',
    regularityUnsure: 'I am not sure', regularityUnsureHint: 'The app will work it out as you log',
    aboutLabel: 'around', confidenceLow: 'Rough estimate', confidenceMedium: 'Getting more accurate',
    lowConfidenceNote: 'Your cycles vary, so this is a rough guide rather than a date to rely on.',
    irregularNote: 'Your cycle length has varied by {days} days. That is common, but if it keeps changing it is worth mentioning to a nurse or doctor.',
    cycleSettings: 'Cycle', changeAnswer: 'Change',
    thisWeek: 'this week', ofGoal: 'of goal', takenToday: 'taken today',
    tapToStart: 'Tap to start', hydration: 'Hydration', nothingDue: 'Nothing due',
    dayShort: 'd', streakShort: 'streak',
    mapView: 'Map', listView: 'List', useMyLocation: 'Use my location',
    locationDenied: 'Location is off, so we cannot sort by distance. You can still search and call.',
    kmAway: 'km away', directions: 'Directions',
    deleteAccountTitle: 'Delete your account?',
    deleteAccountBody: 'This removes everything you have saved in Imara Afya. It cannot be undone and we cannot recover it for you.',
    deleteItemRecords: 'Health records and attachments',
    deleteItemMeds: 'Medicines and dose history',
    deleteItemCycles: 'Cycle and pregnancy tracking',
    deleteItemHabits: 'Water, sleep and weight logs',
    deleteItemAccount: 'Your account and profile',
    deleteNoUndo: 'This is permanent.',
    deleteConfirmPassword: 'Enter your password to confirm',
    deleteKeepAccount: 'Keep my account',
    deleteConfirmCta: 'Delete everything',
    deleteAccountAction: 'Delete account', accountDeleted: 'Your account has been deleted',
  },
  sw: {
    welcomeBack: 'Karibu tena',
    loginSub: 'Ingia ili kuendeleza afya yako.',
    createAccount: 'Fungua akaunti',
    signupSub: 'Anza safari yako ya afya bora.',
    name: 'Jina kamili', namePh: 'mf. Jina Lako',
    email: 'Barua pepe', emailPh: 'wewe@mfano.com',
    password: 'Nywila', passwordPh: '••••••••',
    create: 'Fungua akaunti', login: 'Ingia',
    forgot: 'Umesahau nywila?',
    remember: 'Nikumbuke',
    noAccount: 'Huna akaunti?', haveAccount: 'Una akaunti tayari?',
    signup: 'Jisajili', loginLink: 'Ingia',
    continueWith: 'au endelea na',
    terms: 'Nakubali Masharti na Sera ya Faragha',
    errEmail: 'Weka barua pepe sahihi',
    errPwShort: 'Tumia angalau herufi 8',
    errName: 'Tafadhali weka jina lako',
    errTerms: 'Tafadhali kubali masharti ili kuendelea',
    errGeneric: 'Hitilafu imetokea. Tafadhali jaribu tena.',
    errSocialUnavailable: 'Njia hii ya kuingia haipatikani bado. Tafadhali tumia barua pepe.',
    weak: 'Dhaifu', fair: 'Wastani', good: 'Nzuri', strong: 'Imara',
    successTitle: 'Uko tayari!', successLoginTitle: 'Karibu tena!',
    successSub: 'Tunakupeleka kwenye dashibodi yako ya afya…',
    tagline: 'Afya yako, kwa urahisi.',
    verifyTitle: 'Thibitisha barua pepe yako',
    verifySub: 'Weka nambari ya tarakimu 6 tuliyotuma kwa',
    verifyCta: 'Thibitisha', resend: 'Tuma tena nambari', resendIn: 'Tuma tena baada ya',
    noCode: 'Hukupata nambari?',
    codeErr: 'Nambari si sahihi. Jaribu tena.',
    verifiedTitle: 'Barua pepe imethibitishwa!', verifiedSub: 'Sasa tusanidi wasifu wako…',
    profileTitle: 'Sanidi wasifu wako',
    profileSub: 'Maelezo machache ili kuboresha huduma yako.',
    addPhoto: 'Ongeza picha', changePhoto: 'Badilisha picha',
    genderLabel: 'Jinsia', genderFemale: 'Mwanamke', genderMale: 'Mwanaume', genderOther: 'Nyingine',
    genderWoman: 'Mwanamke', genderMan: 'Mwanaume', errGender: 'Tafadhali chagua jinsia yako',
    heightLabel: 'Urefu (cm)', heightPh: 'mf. 170',
    weightLabel: 'Uzito (kg)', weightPh: 'mf. 65',
    religionLabel: 'Dini', religionPh: 'Chagua dini yako',
    religions: ['Ukristo', 'Uislamu', 'Uhindu', 'Ubuddha', 'Kiasili', 'Hakuna', 'Sipendi kusema'],
    finish: 'Maliza usanidi', skip: 'Ruka kwa sasa', optional: 'Si lazima',
    profileSaved: 'Wasifu umehifadhiwa',
    home: 'Nyumbani', signOut: 'Toka',
    goodMorning: 'Habari ya asubuhi', goodAfternoon: 'Habari ya mchana', goodEvening: 'Habari ya jioni',
    quickActions: 'Vitendo vya haraka', viewAll: 'Ona vyote',
    statRecords: 'Kumbukumbu', statMedsDue: 'Dawa leo', statNextPeriod: 'Hedhi ijayo',
    daysShort: 'siku', daysToGo: 'siku zimebaki',
    healthRecords: 'Kumbukumbu za afya', savedLower: 'zimehifadhiwa', addFirstRecord: 'Ongeza ya kwanza',
    findCare: 'Tafuta huduma', clinicsNearYou: 'Kliniki karibu nawe',
    medications: 'Dawa', dueToday: 'za leo', allDone: 'Umemaliza leo',
    periodTracker: 'Kufuatilia hedhi', trackWellness: 'Fuatilia mzunguko wako',
    myProfile: 'Wasifu wangu', planFree: 'Mpango wa bure', planPremium: 'Mpango wa premium',
    medicationsToday: 'Dawa za leo', noMedications: 'Hakuna dawa bado',
    doseLogged: 'Dozi imerekodiwa',
    firstNameLabel: 'Jina la kwanza', lastNameLabel: 'Jina la ukoo', saveChanges: 'Hifadhi mabadiliko',
    recordsTitle: 'Kumbukumbu za afya', recordsSub: 'Magonjwa, mzio na dawa unazohifadhi',
    addRecord: 'Ongeza kumbukumbu', editRecord: 'Hariri kumbukumbu', newRecord: 'Kumbukumbu mpya',
    recordTypeLabel: 'Aina', recordNameLabel: 'Jina', recordNamePh: 'mf. Pumu',
    recordNoteLabel: 'Maelezo', recordNotePh: 'Chochote cha kukumbuka (si lazima)',
    typeCondition: 'Ugonjwa', typeAllergy: 'Mzio', typeMedication: 'Dawa',
    filterAll: 'Zote',
    noRecords: 'Hakuna kumbukumbu bado', noRecordsSub: 'Ongeza magonjwa, mzio na dawa zako ili ziwe nawe kila wakati.',
    recordSaved: 'Kumbukumbu imehifadhiwa', recordRemoved: 'Kumbukumbu imeondolewa',
    errRecordName: 'Tafadhali weka jina',
    removeRecordTitle: 'Ondoa kumbukumbu hii?', removeRecordBody: 'Haiwezi kurudishwa.',
    cancel: 'Ghairi', remove: 'Ondoa', save: 'Hifadhi',
    tabHome: 'Nyumbani', tabRecords: 'Kumbukumbu', tabMeds: 'Dawa', tabCycle: 'Mzunguko', tabProfile: 'Wasifu',
    medsTitle: 'Dawa', medsSub: 'Unachotumia, na lini',
    addMedication: 'Ongeza dawa', editMedication: 'Hariri dawa', newMedication: 'Dawa mpya',
    medNameLabel: 'Dawa', medNamePh: 'mf. Paracetamol',
    dosageLabel: 'Kipimo', dosagePh: 'mf. 500mg, kidonge 1',
    timesLabel: 'Nyakati', timesPh: 'mf. 08:00, 20:00', timesHint: 'Tenganisha kila saa kwa koma',
    activeMeds: 'Zinazotumika', pausedMeds: 'Zimesimamishwa',
    pause: 'Simamisha', resume: 'Endelea', taken: 'Imetumika', markTaken: 'Weka imetumika',
    medSaved: 'Dawa imehifadhiwa', medRemoved: 'Dawa imeondolewa',
    errMedName: 'Tafadhali weka jina la dawa', errTimeFormat: 'Tumia saa za 24 kama 08:00',
    removeMedTitle: 'Ondoa dawa hii?', removeMedBody: 'Historia ya vikumbusho itabaki.',
    cycleTitle: 'Kifuatiliaji cha hedhi', cycleSub: 'Weka mzunguko wako uone kinachofuata',
    logPeriodCta: 'Weka hedhi ya leo', periodLogged: 'Hedhi imewekwa',
    nextPeriodIn: 'Hedhi ijayo baada ya', fertileWindowIn: 'Kipindi cha uzazi baada ya',
    avgCycle: 'Wastani wa mzunguko', basedOn: 'Kwa msingi wa', cyclesLower: 'mizunguko',
    cycleHistory: 'Historia', ongoing: 'Inaendelea',
    noCycles: 'Hakuna mizunguko bado', noCyclesSub: 'Weka siku ya kwanza ya hedhi yako na utabiri utaonekana hapa.',
    predictionNote: 'Utabiri ni makadirio, si ushauri wa daktari.',
    tabHabits: 'Mazoea', tabMore: 'Zaidi',
    habitsTitle: 'Mazoea ya kila siku', habitsSub: 'Mambo madogo, kila siku',
    waterTitle: 'Maji', glasses: 'vikombe', goalLabel: 'Lengo', addGlass: 'Ongeza kikombe',
    streakLabel: 'siku mfululizo', goalMet: 'Lengo limefikiwa leo',
    sleepTitle: 'Usingizi', sleepLast: 'Usiku uliopita', hoursShort: 'saa',
    logSleep: 'Weka usingizi', sleepPh: 'mf. 7.5',
    weightTitle: 'Uzito', kgShort: 'kg', logWeight: 'Weka uzito',
    bmiLabel: 'BMI', bmiUnderweight: 'Uzito mdogo', bmiNormal: 'Kawaida',
    bmiOverweight: 'Uzito zaidi', bmiObese: 'Unene uliopitiliza',
    bmiNeedsProfile: 'Weka urefu wako kwenye wasifu ili kuona BMI',
    waterGoalTitle: 'Lengo la maji kwa siku', habitLogged: 'Imewekwa', goalSaved: 'Lengo limebadilishwa',
    errNumber: 'Tafadhali weka namba',
    ramadanTitle: 'Hali ya Ramadhani', ramadanSub: 'Badilisha vikumbusho vya dawa kulingana na saumu',
    ramadanOn: 'Hali ya Ramadhani imewashwa', ramadanOff: 'Hali ya Ramadhani imezimwa',
    suhoorLabel: 'Daku', iftarLabel: 'Futari', timePh: '04:30',
    ramadanSaved: 'Mipangilio ya Ramadhani imehifadhiwa',
    errTimesNeeded: 'Weka saa za daku na futari',
    errSuhoorOrder: 'Daku lazima itangulie futari',
    adjustedTitle: 'Saa zilizorekebishwa', originalLabel: 'Kawaida', adjustedLabel: 'Wakati wa saumu',
    noShift: 'Hakuna saa zinazohitaji kubadilishwa', noMedsForRamadan: 'Ongeza dawa zako uone saa zilizorekebishwa',
    ramadanDisclaimer:
      'Hii inabadilisha vikumbusho tu. Muulize daktari au mfamasia kabla ya kubadilisha wakati wa kutumia dawa, na kabla ya kufunga ukiwa na ugonjwa.',
    moreTitle: 'Zaidi', moreSub: 'Kila kitu kingine katika Imara Afya',
    guidanceTitle: 'Mwongozo', guidanceSub: 'Mwongozo wa afya na dini',
    findCareTitle: 'Tafuta huduma', findCareSub: 'Hospitali na kliniki karibu nawe',
    comingSoon: 'Inakuja hivi karibuni',
    languageTitle: 'Lugha', languageSub: 'Chagua lugha ya programu',
    languageChanged: 'Lugha imebadilishwa', settingsTitle: 'Mipangilio',
    careTitle: 'Tafuta huduma', careSub: 'Hospitali, kliniki na maduka ya dawa',
    searchCarePh: 'Tafuta kwa jina au eneo',
    typeHospital: 'Hospitali', typeClinic: 'Kliniki', typePharmacy: 'Maduka ya dawa',
    callFacility: 'Piga simu', noPhone: 'Hakuna namba ya simu',
    noFacilities: 'Hakuna vituo bado',
    noFacilitiesSub: 'Orodha ya eneo lako bado inaandaliwa. Tafadhali angalia tena hivi karibuni.',
    noSearchResults: 'Hakuna kilichopatikana',
    emergencyNote: 'Kwa dharura, nenda hospitali iliyo karibu mara moja.',
    endPeriodCta: 'Hedhi imeisha leo', periodEnded: 'Hedhi imewekwa kuwa imeisha',
    periodOngoing: 'Hedhi inaendelea', startedOn: 'Ilianza', dayCount: 'siku', dayCountPlural: 'siku',
    avgPeriod: 'Muda wa hedhi', editCycle: 'Hariri hedhi',
    startDateLabel: 'Tarehe ya kuanza', endDateLabel: 'Tarehe ya mwisho', datePh: 'MWAKA-MWEZI-SIKU',
    stillOngoing: 'Bado inaendelea', markFinished: 'Weka imeisha',
    cycleSaved: 'Hedhi imesasishwa', cycleRemoved: 'Hedhi imeondolewa',
    removeCycleTitle: 'Ondoa hedhi hii?', removeCycleBody: 'Haitahesabiwa tena katika utabiri wako.',
    errDateFormat: 'Tumia muundo YYYY-MM-DD',
    calendarTitle: 'Kalenda', chartTitle: 'Urefu wa mzunguko',
    legendPeriod: 'Hedhi', legendPredicted: 'Inatarajiwa', legendFertile: 'Uzazi',
    chartNeedsMore: 'Weka mizunguko michache zaidi ili kuona jinsi urefu wake unavyobadilika.',
    logOnDate: 'Weka hedhi iliyoanza', logOnDateBody: 'Hii itahifadhiwa kama siku ya kwanza ya hedhi yako.',
    confirm: 'Thibitisha',
    logPeriodAny: 'Weka hedhi', logToday: 'Ilianza leo', pickOnCalendar: 'Chagua siku hapa chini',
    regularityQuestion: 'Je, mzunguko wako hutabirika?',
    regularitySub: 'Hii hubadilisha kiasi programu inavyoamini utabiri wake. Unaweza kubadilisha jibu wakati wowote.',
    regularityRegular: 'Ndiyo, ni wa kawaida', regularityRegularHint: 'Huja karibu wakati uleule kila mwezi',
    regularityIrregular: 'Hapana, hubadilika sana', regularityIrregularHint: 'Muda hubadilika kila mwezi',
    regularityUnsure: 'Sina uhakika', regularityUnsureHint: 'Programu itagundua unapoweka taarifa',
    aboutLabel: 'takriban', confidenceLow: 'Makadirio', confidenceMedium: 'Inazidi kuwa sahihi',
    lowConfidenceNote: 'Mizunguko yako hubadilika, hivyo hii ni mwongozo tu, si tarehe ya kutegemea.',
    irregularNote: 'Urefu wa mzunguko wako umebadilika kwa siku {days}. Ni jambo la kawaida, lakini likiendelea ni vyema kumweleza muuguzi au daktari.',
    cycleSettings: 'Mzunguko', changeAnswer: 'Badilisha',
    thisWeek: 'wiki hii', ofGoal: 'ya lengo', takenToday: 'zimetumika leo',
    tapToStart: 'Gusa kuanza', hydration: 'Unywaji maji', nothingDue: 'Hakuna inayohitajika',
    dayShort: 'si', streakShort: 'mfululizo',
    mapView: 'Ramani', listView: 'Orodha', useMyLocation: 'Tumia mahali nilipo',
    locationDenied: 'Mahali pamezimwa, hivyo hatuwezi kupanga kwa umbali. Bado unaweza kutafuta na kupiga simu.',
    kmAway: 'km kutoka hapa', directions: 'Maelekezo',
    deleteAccountTitle: 'Futa akaunti yako?',
    deleteAccountBody: 'Hii itaondoa kila kitu ulichohifadhi katika Imara Afya. Haiwezi kurudishwa na hatuwezi kukurudishia.',
    deleteItemRecords: 'Kumbukumbu za afya na viambatisho',
    deleteItemMeds: 'Dawa na historia ya matumizi',
    deleteItemCycles: 'Ufuatiliaji wa hedhi na ujauzito',
    deleteItemHabits: 'Kumbukumbu za maji, usingizi na uzito',
    deleteItemAccount: 'Akaunti na wasifu wako',
    deleteNoUndo: 'Hii ni ya kudumu.',
    deleteConfirmPassword: 'Weka nywila yako kuthibitisha',
    deleteKeepAccount: 'Nataka kuweka akaunti yangu',
    deleteConfirmCta: 'Futa kila kitu',
    deleteAccountAction: 'Futa akaunti', accountDeleted: 'Akaunti yako imefutwa',
  },
  fr: {
    welcomeBack: 'Bon retour',
    loginSub: 'Connectez-vous pour suivre votre santé.',
    createAccount: 'Créer un compte',
    signupSub: 'Commencez votre parcours vers une meilleure santé.',
    name: 'Nom complet', namePh: 'ex. Non complet',
    email: 'E-mail', emailPh: 'vous@exemple.com',
    password: 'Mot de passe', passwordPh: '••••••••',
    create: 'Créer un compte', login: 'Se connecter',
    forgot: 'Mot de passe oublié ?',
    remember: 'Se souvenir de moi',
    noAccount: 'Vous n’avez pas de compte ?', haveAccount: 'Vous avez déjà un compte ?',
    signup: 'S’inscrire', loginLink: 'Se connecter',
    continueWith: 'ou continuer avec',
    terms: 'J’accepte les Conditions et la Politique de confidentialité',
    errEmail: 'Saisissez une adresse e-mail valide',
    errPwShort: 'Utilisez au moins 8 caractères',
    errName: 'Veuillez saisir votre nom',
    errTerms: 'Veuillez accepter les conditions pour continuer',
    errGeneric: 'Une erreur s’est produite. Veuillez réessayer.',
    errSocialUnavailable: 'Cette option de connexion n’est pas encore disponible. Utilisez l’e-mail.',
    weak: 'Faible', fair: 'Moyen', good: 'Bon', strong: 'Fort',
    successTitle: 'Tout est prêt !', successLoginTitle: 'Bon retour !',
    successSub: 'Redirection vers votre tableau de bord santé…',
    tagline: 'Votre santé, en toute simplicité.',
    verifyTitle: 'Vérifiez votre e-mail',
    verifySub: 'Saisissez le code à 6 chiffres envoyé à',
    verifyCta: 'Vérifier', resend: 'Renvoyer le code', resendIn: 'Renvoyer dans',
    noCode: 'Pas reçu de code ?',
    codeErr: 'Code incorrect. Réessayez.',
    verifiedTitle: 'E-mail vérifié !', verifiedSub: 'Configurons votre profil…',
    profileTitle: 'Configurez votre profil',
    profileSub: 'Quelques détails pour personnaliser vos soins.',
    addPhoto: 'Ajouter une photo', changePhoto: 'Changer la photo',
    genderLabel: 'Genre', genderFemale: 'Femme', genderMale: 'Homme', genderOther: 'Autre',
    genderWoman: 'Femme', genderMan: 'Homme', errGender: 'Veuillez sélectionner votre genre',
    heightLabel: 'Taille (cm)', heightPh: 'ex. 170',
    weightLabel: 'Poids (kg)', weightPh: 'ex. 65',
    religionLabel: 'Religion', religionPh: 'Choisissez votre religion',
    religions: ['Christianisme', 'Islam', 'Hindouisme', 'Bouddhisme', 'Traditionnelle', 'Aucune', 'Préfère ne pas dire'],
    finish: 'Terminer', skip: 'Ignorer pour l’instant', optional: 'Facultatif',
    profileSaved: 'Profil enregistré',
    home: 'Accueil', signOut: 'Se déconnecter',
    goodMorning: 'Bonjour', goodAfternoon: 'Bon après-midi', goodEvening: 'Bonsoir',
    quickActions: 'Actions rapides', viewAll: 'Tout voir',
    statRecords: 'Dossiers', statMedsDue: 'Médicaments', statNextPeriod: 'Prochaines règles',
    daysShort: 'j', daysToGo: 'jours restants',
    healthRecords: 'Dossier santé', savedLower: 'enregistrés', addFirstRecord: 'Ajoutez le premier',
    findCare: 'Trouver des soins', clinicsNearYou: 'Cliniques près de vous',
    medications: 'Médicaments', dueToday: "aujourd'hui", allDone: 'Terminé pour aujourd’hui',
    periodTracker: 'Suivi des règles', trackWellness: 'Suivez votre cycle',
    myProfile: 'Mon profil', planFree: 'Formule gratuite', planPremium: 'Formule premium',
    medicationsToday: 'Médicaments du jour', noMedications: 'Aucun médicament',
    doseLogged: 'Dose enregistrée',
    firstNameLabel: 'Prénom', lastNameLabel: 'Nom', saveChanges: 'Enregistrer',
    recordsTitle: 'Dossier santé', recordsSub: 'Maladies, allergies et médicaments que vous conservez',
    addRecord: 'Ajouter', editRecord: 'Modifier', newRecord: 'Nouvelle entrée',
    recordTypeLabel: 'Type', recordNameLabel: 'Nom', recordNamePh: 'ex. Asthme',
    recordNoteLabel: 'Note', recordNotePh: 'À retenir (facultatif)',
    typeCondition: 'Maladie', typeAllergy: 'Allergie', typeMedication: 'Médicament',
    filterAll: 'Tout',
    noRecords: 'Aucune entrée', noRecordsSub: 'Ajoutez vos maladies, allergies et médicaments pour les avoir toujours avec vous.',
    recordSaved: 'Entrée enregistrée', recordRemoved: 'Entrée supprimée',
    errRecordName: 'Veuillez saisir un nom',
    removeRecordTitle: 'Supprimer cette entrée ?', removeRecordBody: 'Cette action est irréversible.',
    cancel: 'Annuler', remove: 'Supprimer', save: 'Enregistrer',
    tabHome: 'Accueil', tabRecords: 'Dossier', tabMeds: 'Médicaments', tabCycle: 'Cycle', tabProfile: 'Profil',
    medsTitle: 'Médicaments', medsSub: 'Ce que vous prenez, et quand',
    addMedication: 'Ajouter', editMedication: 'Modifier', newMedication: 'Nouveau médicament',
    medNameLabel: 'Médicament', medNamePh: 'ex. Paracétamol',
    dosageLabel: 'Dose', dosagePh: 'ex. 500mg, 1 comprimé',
    timesLabel: 'Horaires', timesPh: 'ex. 08:00, 20:00', timesHint: 'Séparez chaque heure par une virgule',
    activeMeds: 'Actifs', pausedMeds: 'En pause',
    pause: 'Mettre en pause', resume: 'Reprendre', taken: 'Pris', markTaken: 'Marquer pris',
    medSaved: 'Médicament enregistré', medRemoved: 'Médicament supprimé',
    errMedName: 'Veuillez saisir le nom du médicament', errTimeFormat: 'Utilisez le format 24h, ex. 08:00',
    removeMedTitle: 'Supprimer ce médicament ?', removeMedBody: 'L’historique des rappels sera conservé.',
    cycleTitle: 'Suivi des règles', cycleSub: 'Enregistrez votre cycle pour voir la suite',
    logPeriodCta: 'Enregistrer aujourd’hui', periodLogged: 'Règles enregistrées',
    nextPeriodIn: 'Prochaines règles dans', fertileWindowIn: 'Fenêtre fertile dans',
    avgCycle: 'Cycle moyen', basedOn: 'Basé sur', cyclesLower: 'cycles',
    cycleHistory: 'Historique', ongoing: 'En cours',
    noCycles: 'Aucun cycle enregistré', noCyclesSub: 'Enregistrez le premier jour de vos règles et les prévisions apparaîtront ici.',
    predictionNote: 'Les prévisions sont des estimations, pas un avis médical.',
    tabHabits: 'Habitudes', tabMore: 'Plus',
    habitsTitle: 'Habitudes du jour', habitsSub: 'De petites choses, chaque jour',
    waterTitle: 'Eau', glasses: 'verres', goalLabel: 'Objectif', addGlass: 'Ajouter un verre',
    streakLabel: 'jours de suite', goalMet: 'Objectif atteint aujourd’hui',
    sleepTitle: 'Sommeil', sleepLast: 'La nuit dernière', hoursShort: 'h',
    logSleep: 'Enregistrer', sleepPh: 'ex. 7.5',
    weightTitle: 'Poids', kgShort: 'kg', logWeight: 'Enregistrer',
    bmiLabel: 'IMC', bmiUnderweight: 'Insuffisance pondérale', bmiNormal: 'Normal',
    bmiOverweight: 'Surpoids', bmiObese: 'Obésité',
    bmiNeedsProfile: 'Ajoutez votre taille dans le profil pour voir l’IMC',
    waterGoalTitle: 'Objectif d’eau quotidien', habitLogged: 'Enregistré', goalSaved: 'Objectif mis à jour',
    errNumber: 'Veuillez saisir un nombre',
    ramadanTitle: 'Mode Ramadan', ramadanSub: 'Décalez les rappels autour de votre jeûne',
    ramadanOn: 'Mode Ramadan activé', ramadanOff: 'Mode Ramadan désactivé',
    suhoorLabel: 'Suhoor', iftarLabel: 'Iftar', timePh: '04:30',
    ramadanSaved: 'Paramètres Ramadan enregistrés',
    errTimesNeeded: 'Renseignez le suhoor et l’iftar',
    errSuhoorOrder: 'Le suhoor doit précéder l’iftar',
    adjustedTitle: 'Horaires ajustés', originalLabel: 'Normalement', adjustedLabel: 'Pendant le jeûne',
    noShift: 'Aucun horaire à déplacer', noMedsForRamadan: 'Ajoutez vos médicaments pour voir les horaires ajustés',
    ramadanDisclaimer:
      'Ceci ne modifie que les rappels. Consultez votre médecin ou pharmacien avant de changer l’heure de prise d’un médicament, et avant de jeûner avec une maladie.',
    moreTitle: 'Plus', moreSub: 'Tout le reste dans Imara Afya',
    guidanceTitle: 'Conseils', guidanceSub: 'Conseils santé et religieux',
    findCareTitle: 'Trouver des soins', findCareSub: 'Hôpitaux et cliniques près de vous',
    comingSoon: 'Bientôt disponible',
    languageTitle: 'Langue', languageSub: 'Choisissez la langue de l’application',
    languageChanged: 'Langue modifiée', settingsTitle: 'Paramètres',
    careTitle: 'Trouver des soins', careSub: 'Hôpitaux, cliniques et pharmacies',
    searchCarePh: 'Rechercher par nom ou quartier',
    typeHospital: 'Hôpitaux', typeClinic: 'Cliniques', typePharmacy: 'Pharmacies',
    callFacility: 'Appeler', noPhone: 'Pas de numéro',
    noFacilities: 'Aucun établissement répertorié',
    noFacilitiesSub: 'L’annuaire de votre région est en cours de constitution. Revenez bientôt.',
    noSearchResults: 'Aucun résultat',
    emergencyNote: 'En cas d’urgence, rendez-vous immédiatement à l’hôpital le plus proche.',
    endPeriodCta: 'Règles terminées aujourd’hui', periodEnded: 'Règles marquées comme terminées',
    periodOngoing: 'Règles en cours', startedOn: 'Début', dayCount: 'jour', dayCountPlural: 'jours',
    avgPeriod: 'Durée des règles', editCycle: 'Modifier',
    startDateLabel: 'Date de début', endDateLabel: 'Date de fin', datePh: 'AAAA-MM-JJ',
    stillOngoing: 'Toujours en cours', markFinished: 'Marquer terminé',
    cycleSaved: 'Règles mises à jour', cycleRemoved: 'Règles supprimées',
    removeCycleTitle: 'Supprimer ces règles ?', removeCycleBody: 'Elles ne compteront plus dans vos prévisions.',
    errDateFormat: 'Utilisez le format AAAA-MM-JJ',
    calendarTitle: 'Calendrier', chartTitle: 'Durée du cycle',
    legendPeriod: 'Règles', legendPredicted: 'Prévu', legendFertile: 'Fertile',
    chartNeedsMore: 'Enregistrez quelques cycles de plus pour voir comment leur durée varie.',
    logOnDate: 'Enregistrer des règles commençant le', logOnDateBody: 'Ce sera enregistré comme le premier jour de vos règles.',
    confirm: 'Confirmer',
    logPeriodAny: 'Enregistrer des règles', logToday: 'Elles ont commencé aujourd’hui', pickOnCalendar: 'Choisissez le jour ci-dessous',
    regularityQuestion: 'Votre cycle est-il généralement régulier ?',
    regularitySub: 'Cela change la confiance accordée aux prévisions. Vous pouvez modifier votre réponse à tout moment.',
    regularityRegular: 'Oui, il est régulier', regularityRegularHint: 'Il arrive à peu près au même moment chaque mois',
    regularityIrregular: 'Non, il varie beaucoup', regularityIrregularHint: 'L’écart change d’un mois à l’autre',
    regularityUnsure: 'Je ne sais pas', regularityUnsureHint: 'L’application le déterminera au fil de vos saisies',
    aboutLabel: 'environ', confidenceLow: 'Estimation', confidenceMedium: 'De plus en plus précis',
    lowConfidenceNote: 'Vos cycles sont variables, donc ceci est une indication et non une date sur laquelle compter.',
    irregularNote: 'La durée de votre cycle a varié de {days} jours. C’est courant, mais si cela persiste, parlez-en à un soignant.',
    cycleSettings: 'Cycle', changeAnswer: 'Modifier',
    thisWeek: 'cette semaine', ofGoal: 'de l’objectif', takenToday: 'pris aujourd’hui',
    tapToStart: 'Appuyez pour commencer', hydration: 'Hydratation', nothingDue: 'Rien à prendre',
    dayShort: 'j', streakShort: 'série',
    mapView: 'Carte', listView: 'Liste', useMyLocation: 'Utiliser ma position',
    locationDenied: 'La localisation est désactivée, impossible de trier par distance. Vous pouvez toujours rechercher et appeler.',
    kmAway: 'km', directions: 'Itinéraire',
    deleteAccountTitle: 'Supprimer votre compte ?',
    deleteAccountBody: 'Cela supprime tout ce que vous avez enregistré dans Imara Afya. C’est irréversible et nous ne pourrons rien récupérer.',
    deleteItemRecords: 'Dossier santé et pièces jointes',
    deleteItemMeds: 'Médicaments et historique des prises',
    deleteItemCycles: 'Suivi des règles et de la grossesse',
    deleteItemHabits: 'Relevés d’eau, de sommeil et de poids',
    deleteItemAccount: 'Votre compte et votre profil',
    deleteNoUndo: 'Cette action est définitive.',
    deleteConfirmPassword: 'Saisissez votre mot de passe pour confirmer',
    deleteKeepAccount: 'Garder mon compte',
    deleteConfirmCta: 'Tout supprimer',
    deleteAccountAction: 'Supprimer le compte', accountDeleted: 'Votre compte a été supprimé',
  },
  rn: {
    welcomeBack: 'Murakaza neza',
    loginSub: 'Injira kugira ukurikirane amagara yawe.',
    createAccount: 'Fungura konte',
    signupSub: 'Tangura urugendo rwawe rw’amagara meza.',
    name: 'Izina ryuzuye', namePh: 'akarorero Amazin Yawe',
    email: 'Imeyili', emailPh: 'wewe@akarorero.com',
    password: 'Ijambo ry’ibanga', passwordPh: '••••••••',
    create: 'Fungura konte', login: 'Injira',
    forgot: 'Wibagiwe ijambo ry’ibanga?',
    remember: 'Unyibuke',
    noAccount: 'Nta konte ufise?', haveAccount: 'Usanzwe ufise konte?',
    signup: 'Iyandikishe', loginLink: 'Injira',
    continueWith: 'canke winjire ukoresheje',
    terms: 'Ndemera Amabwirizwa n’Ipolitike y’ibanga',
    errEmail: 'Andika imeyili nyayo',
    errPwShort: 'Koresha nibura inyuguti 8',
    errName: 'Andika izina ryawe',
    errTerms: 'Emera amabwirizwa kugira ubandanye',
    errGeneric: 'Habaye ikibazo. Subira ugerageze.',
    errSocialUnavailable: 'Ubu buryo bwo kwinjira ntiburaboneka. Koresha imeyili.',
    weak: 'Ridakomeye', fair: 'Risanzwe', good: 'Ryiza', strong: 'Rikomeye',
    successTitle: 'Vyose birarangiye!', successLoginTitle: 'Murakaza neza!',
    successSub: 'Turiko turakujana ku rupapuro rwawe rw’amagara…',
    tagline: 'Amagara yawe, mu buryo bworoshe.',
    verifyTitle: 'Emeza imeyili yawe',
    verifySub: 'Andika kode y’imibare 6 twakwoherereje kuri',
    verifyCta: 'Emeza', resend: 'Subira wohereze kode', resendIn: 'Subira mu',
    noCode: 'Ntiwakiriye kode?',
    codeErr: 'Iyo kode siyo. Gerageza.',
    verifiedTitle: 'Imeyili yemejwe!', verifiedSub: 'Ubu reka dushireho umwidondoro wawe…',
    profileTitle: 'Shiraho umwidondoro wawe',
    profileSub: 'Amakuru make kugira twongere ubuvuzi bwawe.',
    addPhoto: 'Ongeraho ifoto', changePhoto: 'Hindura ifoto',
    genderLabel: 'Igitsina', genderFemale: 'Umugore', genderMale: 'Umugabo', genderOther: 'Ikindi',
    genderWoman: 'Umugore', genderMan: 'Umugabo', errGender: 'Hitamwo igitsina cawe',
    heightLabel: 'Uburebure (cm)', heightPh: 'akarorero 170',
    weightLabel: 'Ibiro (kg)', weightPh: 'akarorero 65',
    religionLabel: 'Idini', religionPh: 'Hitamwo idini ryawe',
    religions: ['Ubukirisu', 'Ubuyisilamu', 'Ubuhindu', 'Ububuda', 'Gakondo', 'Nta na rimwe', 'Sinshaka kuvuga'],
    finish: 'Rangiza', skip: 'Simba kuri ubu', optional: 'Si itegeko',
    profileSaved: 'Umwidondoro warabitswe',
    home: 'Ahabanza', signOut: 'Sohoka',
    goodMorning: 'Mwaramutse', goodAfternoon: 'Mwiriwe', goodEvening: 'Mwiriwe',
    quickActions: 'Ibikorwa vyihuta', viewAll: 'Raba vyose',
    statRecords: 'Amakuru', statMedsDue: 'Imiti y’uyu musi', statNextPeriod: 'Imihango itaha',
    daysShort: 'im', daysToGo: 'imisi isigaye',
    healthRecords: 'Amakuru y’amagara', savedLower: 'yabitswe', addFirstRecord: 'Ongeraho aya mbere',
    findCare: 'Rondera ubuvuzi', clinicsNearYou: 'Amavuriro yegereye',
    medications: 'Imiti', dueToday: 'y’uyu musi', allDone: 'Warangije uyu musi',
    periodTracker: 'Gukurikirana imihango', trackWellness: 'Kurikirana imihango yawe',
    myProfile: 'Umwidondoro wanje', planFree: 'Uburyo bw’ubuntu', planPremium: 'Uburyo bwa premium',
    medicationsToday: 'Imiti y’uyu musi', noMedications: 'Nta miti irahari',
    doseLogged: 'Dozi yanditswe',
    firstNameLabel: 'Izina', lastNameLabel: 'Izina ry’umuryango', saveChanges: 'Bika impinduka',
    recordsTitle: 'Amakuru y’amagara', recordsSub: 'Indwara, ivyo utabona n’imiti ubika',
    addRecord: 'Ongeraho', editRecord: 'Hindura', newRecord: 'Ikinyegeza gishasha',
    recordTypeLabel: 'Ubwoko', recordNameLabel: 'Izina', recordNamePh: 'nk. Asima',
    recordNoteLabel: 'Icete', recordNotePh: 'Ico wokwibuka (ntibisabwa)',
    typeCondition: 'Indwara', typeAllergy: 'Aleriji', typeMedication: 'Umuti',
    filterAll: 'Vyose',
    noRecords: 'Nta makuru arahari', noRecordsSub: 'Ongeraho indwara, aleriji n’imiti vyawe kugira ubigumane.',
    recordSaved: 'Vyabitswe', recordRemoved: 'Vyakuweho',
    errRecordName: 'Andika izina',
    removeRecordTitle: 'Ukuraho ivyanditswe?', removeRecordBody: 'Ntibishobora gusubizwa.',
    cancel: 'Reka', remove: 'Kuraho', save: 'Bika',
    tabHome: 'Ahabanza', tabRecords: 'Amakuru', tabMeds: 'Imiti', tabCycle: 'Ukwezi', tabProfile: 'Umwidondoro',
    medsTitle: 'Imiti', medsSub: 'Ivyo unywa, n’igihe',
    addMedication: 'Ongeraho umuti', editMedication: 'Hindura umuti', newMedication: 'Umuti mushasha',
    medNameLabel: 'Umuti', medNamePh: 'nk. Paracetamol',
    dosageLabel: 'Igipimo', dosagePh: 'nk. 500mg, ikinini 1',
    timesLabel: 'Amasaha', timesPh: 'nk. 08:00, 20:00', timesHint: 'Tandukanya amasaha n’aka kama',
    activeMeds: 'Irakoreshwa', pausedMeds: 'Yahagaritswe',
    pause: 'Hagarika', resume: 'Subira', taken: 'Yanyoywe', markTaken: 'Emeza ko wanyoye',
    medSaved: 'Umuti wabitswe', medRemoved: 'Umuti wakuweho',
    errMedName: 'Andika izina ry’umuti', errTimeFormat: 'Koresha amasaha 24 nka 08:00',
    removeMedTitle: 'Ukuraho uyu muti?', removeMedBody: 'Amakuru y’ibibutsa arabikwa.',
    cycleTitle: 'Gukurikirana amaraso', cycleSub: 'Andika ukwezi kwawe urabe ibikurikira',
    logPeriodCta: 'Andika ay’uyu musi', periodLogged: 'Vyanditswe',
    nextPeriodIn: 'Ayakurikira mu', fertileWindowIn: 'Igihe c’uburumbuke mu',
    avgCycle: 'Impuzandengo y’ukwezi', basedOn: 'Bishingiye ku', cyclesLower: 'kwezi',
    cycleHistory: 'Kahise', ongoing: 'Biriko biraba',
    noCycles: 'Nta kwezi kwanditswe', noCyclesSub: 'Andika umusi wa mbere w’amaraso, ivyo biteganijwe bizoboneka ng’aha.',
    predictionNote: 'Ivyo biteganijwe ni ibigereranyo, si impanuro y’umuganga.',
    tabHabits: 'Ingeso', tabMore: 'Ibindi',
    habitsTitle: 'Ingeso za buri musi', habitsSub: 'Utuntu duto, buri musi',
    waterTitle: 'Amazi', glasses: 'ibirahuri', goalLabel: 'Intumbero', addGlass: 'Ongeraho ikirahuri',
    streakLabel: 'imisi ikurikiranye', goalMet: 'Intumbero yashitse uyu musi',
    sleepTitle: 'Itiro', sleepLast: 'Ijoro riheze', hoursShort: 'am',
    logSleep: 'Andika itiro', sleepPh: 'nk. 7.5',
    weightTitle: 'Uburemere', kgShort: 'kg', logWeight: 'Andika uburemere',
    bmiLabel: 'BMI', bmiUnderweight: 'Uburemere buke', bmiNormal: 'Bisanzwe',
    bmiOverweight: 'Uburemere bwinshi', bmiObese: 'Umubyibuho ukabije',
    bmiNeedsProfile: 'Andika uburebure bwawe mu mwidondoro kugira ubone BMI',
    waterGoalTitle: 'Intumbero y’amazi ku musi', habitLogged: 'Vyanditswe', goalSaved: 'Intumbero yahindutse',
    errNumber: 'Andika igiharuro',
    ramadanTitle: 'Uburyo bwa Ramadhani', ramadanSub: 'Hindura ibibutsa vy’imiti ukurikije ukwisonzesha',
    ramadanOn: 'Uburyo bwa Ramadhani burakora', ramadanOff: 'Uburyo bwa Ramadhani ntibukora',
    suhoorLabel: 'Suhoor', iftarLabel: 'Iftar', timePh: '04:30',
    ramadanSaved: 'Vyabitswe',
    errTimesNeeded: 'Shiraho amasaha ya suhoor na iftar',
    errSuhoorOrder: 'Suhoor itegerezwa kuza imbere ya iftar',
    adjustedTitle: 'Amasaha yahinduwe', originalLabel: 'Bisanzwe', adjustedLabel: 'Mu kwisonzesha',
    noShift: 'Nta masaha akeneye guhindurwa', noMedsForRamadan: 'Ongeraho imiti yawe urabe amasaha yahinduwe',
    ramadanDisclaimer:
      'Ivyo bihindura gusa ibibutsa. Baza umuganga canke umufarumasiye imbere y’uko uhindura igihe unywera umuti, be n’imbere y’uko wisonzesha ufise indwara.',
    moreTitle: 'Ibindi', moreSub: 'Ibindi vyose muri Imara Afya',
    guidanceTitle: 'Ubuyobozi', guidanceSub: 'Ubuyobozi bw’amagara n’ubw’idini',
    findCareTitle: 'Rondera ivyubahiro', findCareSub: 'Ibitaro n’amavuriro hafi yawe',
    comingSoon: 'Biregereje',
    languageTitle: 'Ururimi', languageSub: 'Hitamwo ururimi rw’ikoraniro',
    languageChanged: 'Ururimi rwarahindutse', settingsTitle: 'Amagenamiterere',
    careTitle: 'Rondera ivyubahiro', careSub: 'Ibitaro, amavuriro n’amaduka y’imiti',
    searchCarePh: 'Rondera ku izina canke ikibanza',
    typeHospital: 'Ibitaro', typeClinic: 'Amavuriro', typePharmacy: 'Amaduka y’imiti',
    callFacility: 'Terefona', noPhone: 'Nta nomero ya terefone',
    noFacilities: 'Nta bibanza birashirwaho',
    noFacilitiesSub: 'Urutonde rw’ikibanza cawe rukiri gutegurwa. Uzogarukeyo vuba.',
    noSearchResults: 'Nta co vyabonetse',
    emergencyNote: 'Mu bihe bihutirwa, ja mu bitaro biri hafi ako kanya.',
    endPeriodCta: 'Amaraso yarangiye uyu musi', periodEnded: 'Vyanditswe ko vyarangiye',
    periodOngoing: 'Amaraso ariko araza', startedOn: 'Vyatanguye', dayCount: 'umusi', dayCountPlural: 'imisi',
    avgPeriod: 'Igihe amaraso amara', editCycle: 'Hindura',
    startDateLabel: 'Itariki vyatangiye', endDateLabel: 'Itariki vyarangiriye', datePh: 'UMWAKA-UKWEZI-UMUSI',
    stillOngoing: 'Biracariko', markFinished: 'Emeza ko vyarangiye',
    cycleSaved: 'Vyahinduwe', cycleRemoved: 'Vyakuweho',
    removeCycleTitle: 'Ukuraho aya maraso?', removeCycleBody: 'Ntibizoba bikibariwe mu vyo biteganijwe.',
    errDateFormat: 'Koresha uburyo YYYY-MM-DD',
    calendarTitle: 'Kalindari', chartTitle: 'Uburebure bw’ukwezi',
    legendPeriod: 'Amaraso', legendPredicted: 'Biteganijwe', legendFertile: 'Uburumbuke',
    chartNeedsMore: 'Andika ukwezi kwinshi kugira ubone ingene uburebure bwako buhinduka.',
    logOnDate: 'Andika amaraso yatanguye', logOnDateBody: 'Uyu uzoba ari umusi wa mbere w’amaraso yawe.',
    confirm: 'Emeza',
    logPeriodAny: 'Andika amaraso', logToday: 'Yatanguye uyu musi', pickOnCalendar: 'Hitamwo umusi hepfo',
    regularityQuestion: 'Ukwezi kwawe kwama kuza ku gihe?',
    regularitySub: 'Ivyo bihindura ukuntu porogaramu yizigira ivyo iteganya. Urashobora guhindura inyishu igihe ico ari co cose.',
    regularityRegular: 'Ego, kurasanzwe', regularityRegularHint: 'Kuza ku gihe kimwe buri kwezi',
    regularityIrregular: 'Oya, birahinduka cane', regularityIrregularHint: 'Ikiringo gihinduka buri kwezi',
    regularityUnsure: 'Sinzi neza', regularityUnsureHint: 'Porogaramu izobimenya uko wandika',
    aboutLabel: 'nka', confidenceLow: 'Igereranyo', confidenceMedium: 'Biriko birarushiriza kuba vyo',
    lowConfidenceNote: 'Ukwezi kwawe kurahinduka, rero ivyo ni ubuyobozi gusa, si itariki wokwizigira.',
    irregularNote: 'Uburebure bw’ukwezi kwawe bwarahindutse imisi {days}. Birasanzwe, ariko bibandanije ni vyiza kubibwira umuforoma canke umuganga.',
    cycleSettings: 'Ukwezi', changeAnswer: 'Hindura',
    thisWeek: 'iyi ndwi', ofGoal: 'ku ntumbero', takenToday: 'yanyoywe uyu musi',
    tapToStart: 'Kanda utangure', hydration: 'Kunywa amazi', nothingDue: 'Nta co usabwa',
    dayShort: 'um', streakShort: 'ikurikirana',
    mapView: 'Ikarata', listView: 'Urutonde', useMyLocation: 'Koresha aho ndi',
    locationDenied: 'Aho uri ntihazwi, ntitwoshobora gutondeka ku ntera. Urashobora kurondera no guterefona.',
    kmAway: 'km', directions: 'Inzira',
    deleteAccountTitle: 'Gusiba konti yawe?',
    deleteAccountBody: 'Ivyo bizokuraho ivyo wabitse vyose muri Imara Afya. Ntibishobora gusubizwa kandi ntitwoshobora kubigarukana.',
    deleteItemRecords: 'Amakuru y’amagara n’ivyometsweko',
    deleteItemMeds: 'Imiti n’akahise k’ukuyinywa',
    deleteItemCycles: 'Gukurikirana amaraso n’imbanyi',
    deleteItemHabits: 'Ivyanditswe vy’amazi, itiro n’uburemere',
    deleteItemAccount: 'Konti n’umwidondoro wawe',
    deleteNoUndo: 'Ivyo ntibisubirwamwo.',
    deleteConfirmPassword: 'Andika ijambo ryawe ry’ibanga wemeze',
    deleteKeepAccount: 'Ngumane konti yanje',
    deleteConfirmCta: 'Siba vyose',
    deleteAccountAction: 'Gusiba konti', accountDeleted: 'Konti yawe yasibwe',
  },
};

export type LangCode = keyof typeof STRINGS;
export type Strings = (typeof STRINGS)['en'];

type LangContextValue = {
  lang: LangCode;
  setLang: React.Dispatch<React.SetStateAction<LangCode>>;
  t: Strings;
};

const LangContext = createContext<LangContextValue | null>(null);

export function LangProvider({
  children,
  initialLang = 'en',
}: {
  children: ReactNode;
  initialLang?: LangCode;
}) {
  const [lang, setLangState] = useState<LangCode>(initialLang);

  // restore the language the user picked last time they used the app
  useEffect(() => {
    let cancelled = false;

    getLang().then((saved) => {
      if (!cancelled && saved && saved in STRINGS) setLangState(saved as LangCode);
    });

    return () => {
      cancelled = true;
    };
  }, []);

  // same signature as useState's setter, but persists whatever it lands on
  const setLang = useCallback<React.Dispatch<React.SetStateAction<LangCode>>>((next) => {
    setLangState((prev) => {
      const resolved = typeof next === 'function' ? (next as (p: LangCode) => LangCode)(prev) : next;
      if (resolved !== prev) saveLang(resolved);
      return resolved;
    });
  }, []);

  const value = useMemo<LangContextValue>(
    () => ({ lang, setLang, t: (STRINGS[lang] || STRINGS.en) as Strings }),
    [lang, setLang],
  );
  return <LangContext.Provider value={value}>{children}</LangContext.Provider>;
}

export function useStrings() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useStrings must be used inside <LangProvider>');
  return ctx;
}
