plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'bi.imaraco.imaraafya'
version = '1.0.0'

android {
  namespace "expo.modules.sleep"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
  }
}

dependencies {
  // Google Sleep API (ActivityRecognitionClient.requestSleepSegmentUpdates).
  implementation 'com.google.android.gms:play-services-location:21.3.0'
}
